-- =============================================================================
-- GABARITA — 30 Questões: Interpretação de Textos (Estilo COTEC)
-- Fases: 10 Fáceis, 10 Médias, 10 Difíceis
-- Execute no SQL Editor do Supabase
-- IMPORTANTE: Apague as questões anteriores deste tópico antes de rodar, ou apenas rode para somar.
-- =============================================================================

-- Remover questões antigas de Interpretação para evitar duplicidade (Opcional, tire o comentário se quiser limpar)
-- DELETE FROM public.questions WHERE disciplina = 'lingua-portuguesa' AND topico = 'Interpretação de textos';

insert into public.questions (disciplina, topico, nivel_dificuldade, enunciado, opcao_a, opcao_b, opcao_c, opcao_d, gabarito, explicacao) values

-- ==================== FASE 1: FÁCIL (10 Questões) ====================
('lingua-portuguesa', 'Interpretação de textos', 'facil', 'Leia a frase: "O trabalho dignifica o homem, mas o descanso excessivo o acomoda."<br><br>A palavra "mas" estabelece na frase uma relação de:', 'Adição', 'Oposição', 'Conclusão', 'Alternância', 'b', 'A conjunção "mas" é coordenativa adversativa, indicando oposição ou contraste.'),
('lingua-portuguesa', 'Interpretação de textos', 'facil', '"Aquele político é uma raposa felpuda."<br><br>Nesta frase, há o emprego de qual figura de linguagem baseada em uma comparação implícita?', 'Metáfora', 'Eufemismo', 'Hipérbole', 'Metonímia', 'a', 'Metáfora é uma comparação implícita. Chamar alguém de "raposa" atribui a ele as qualidades de esperteza.'),
('lingua-portuguesa', 'Interpretação de textos', 'facil', 'Aviso na porta de um consultório: "É proibido a entrada de pessoas não autorizadas."<br><br>O objetivo principal deste texto é:', 'Informar sobre o horário de funcionamento.', 'Proibir uma ação específica no local.', 'Convidar pessoas para uma reunião.', 'Divulgar um evento médico.', 'b', 'O texto é instrucional/injuntivo com caráter de proibição explícita.'),
('lingua-portuguesa', 'Interpretação de textos', 'facil', '"Choveu muito ontem à noite; logo, as ruas estão alagadas."<br><br>A palavra "logo" indica:', 'Tempo', 'Causa', 'Conclusão', 'Condição', 'c', 'A conjunção "logo" é coordenativa conclusiva, introduzindo o resultado lógico do fato anterior.'),
('lingua-portuguesa', 'Interpretação de textos', 'facil', '"O paciente foi submetido a uma cirurgia de emergência e, graças à rapidez da equipe, passa bem."<br><br>Qual o sentido de "graças a" no trecho?', 'Agradecimento religioso', 'Causa ou motivo', 'Consequência do estado de saúde', 'Finalidade da cirurgia', 'b', '"Graças a" introduz a causa pela qual o paciente passa bem (a rapidez da equipe).'),
('lingua-portuguesa', 'Interpretação de textos', 'facil', '"A prefeitura vai construir uma nova ponte, visto que a antiga desabou."<br><br>A locução "visto que" expressa ideia de:', 'Concessão', 'Conclusão', 'Causa', 'Proporção', 'c', '"Visto que" é uma locução conjuntiva causal, pois explica o motivo de a nova ponte ser construída.'),
('lingua-portuguesa', 'Interpretação de textos', 'facil', 'Na frase "Minha filha, você é a luz da minha vida", a palavra "luz" é usada no sentido:', 'Denotativo, indicando clareza física.', 'Conotativo, indicando importância e alegria.', 'Literal, indicando energia elétrica.', 'Pejorativo, indicando exagero.', 'b', 'Sentido conotativo é o sentido figurado. "Luz" representa alegria, guia, importância.'),
('lingua-portuguesa', 'Interpretação de textos', 'facil', '"Todos os alunos foram aprovados, exceto João, que faltou no dia da prova."<br><br>A palavra "exceto" indica:', 'Uma exclusão ou restrição.', 'Uma adição de informação.', 'Uma explicação detalhada.', 'Uma dúvida do professor.', 'a', '"Exceto" é uma preposição/palavra que indica exclusão, retirando João do grupo dos aprovados.'),
('lingua-portuguesa', 'Interpretação de textos', 'facil', '"Ele correu o mais rápido que pôde para não perder o ônibus."<br><br>Qual é a finalidade da ação de correr?', 'Praticar exercício físico.', 'Não perder o ônibus.', 'Chegar suado no trabalho.', 'Bater um recorde pessoal.', 'b', 'A preposição "para" introduz a oração que expressa a finalidade da ação principal.'),
('lingua-portuguesa', 'Interpretação de textos', 'facil', 'Qual destas frases expressa um "fato" e não uma "opinião"?', 'O filme de ontem foi muito chato.', 'O bolo de chocolate é a melhor sobremesa.', 'A capital do Brasil é Brasília.', 'As segundas-feiras são deprimentes.', 'c', 'A alternativa C traz uma informação objetiva e verificável (fato). As outras trazem juízos de valor (opiniões).'),

-- ==================== FASE 2: MÉDIO (10 Questões) ====================
('lingua-portuguesa', 'Interpretação de textos', 'medio', 'Leia o trecho de edital: "As inscrições deferidas serão publicadas no diário oficial, cabendo recurso no prazo de 48 horas."<br><br>A expressão "cabendo recurso" significa que:', 'O candidato é obrigado a recorrer.', 'O candidato aprovado será punido.', 'É facultado ao candidato contestar a decisão.', 'O diário oficial pode ser alterado a qualquer momento.', 'c', '"Caber recurso" indica que existe a possibilidade/direito (faculdade) de o candidato questionar o resultado.'),
('lingua-portuguesa', 'Interpretação de textos', 'medio', '"Apesar do grande esforço da equipe médica, o quadro do paciente não evoluiu como esperado."<br><br>A locução "apesar do" introduz uma ideia de:', 'Causa inevitável', 'Condição necessária', 'Concessão', 'Proporção', 'c', '"Apesar de" é uma locução prepositiva concessiva. Indica um obstáculo (esforço) que não impediu o resultado (não evoluir).'),
('lingua-portuguesa', 'Interpretação de textos', 'medio', 'Em "O advogado refutou as alegações da testemunha", o verbo "refutar" tem sentido equivalente a:', 'Confirmar', 'Contestar', 'Anotar', 'Ignorar', 'b', 'Refutar significa rebater, contestar, provar a falsidade de um argumento ou alegação.'),
('lingua-portuguesa', 'Interpretação de textos', 'medio', '"O governo implementou medidas austeras para conter a inflação."<br><br>No contexto, "austeras" significa:', 'Gastadoras e irresponsáveis.', 'Modernas e tecnológicas.', 'Rigorosas e severas.', 'Flexíveis e amigáveis.', 'c', 'Austeridade econômica refere-se a cortes de gastos, rigor e severidade financeira.'),
('lingua-portuguesa', 'Interpretação de textos', 'medio', '"Se não chover amanhã, iremos à praia."<br><br>Nesta frase, a oração inicial estabelece uma:', 'Relação de causa e consequência certa.', 'Condição para que a ação principal ocorra.', 'Afirmação temporal sobre o clima.', 'Concessão sobre a ida à praia.', 'b', 'A conjunção "se" introduz uma oração subordinada adverbial condicional.'),
('lingua-portuguesa', 'Interpretação de textos', 'medio', '"As redes sociais criaram bolhas onde o debate frequentemente cede espaço à confirmação de crenças."<br><br>O que o autor quer dizer com "cede espaço à confirmação de crenças"?', 'Que o debate está cada vez mais rico nas redes.', 'Que as pessoas preferem encontrar opiniões iguais às suas a debater o contraditório.', 'Que as crenças religiosas dominam as redes sociais.', 'Que o espaço das redes é muito pequeno para discussões longas.', 'b', 'A "confirmação de crenças" refere-se ao viés de confirmação, onde indivíduos ignoram ideias contrárias e buscam apenas o que já concordam.'),
('lingua-portuguesa', 'Interpretação de textos', 'medio', '"Embora a tecnologia avance, as mazelas sociais persistem."<br><br>A palavra "embora" pode ser substituída sem perda de sentido por:', 'Portanto', 'Contudo', 'Conquanto', 'Visto que', 'c', '"Conquanto" é sinônimo de "embora", ambas são conjunções concessivas.'),
('lingua-portuguesa', 'Interpretação de textos', 'medio', 'O termo "subsequente" em "O pagamento ocorrerá no mês subsequente" significa:', 'No mês anterior.', 'No mesmo mês.', 'No mês seguinte.', 'Em qualquer mês.', 'c', 'Subsequente significa aquilo que vem imediatamente depois (seguinte).'),
('lingua-portuguesa', 'Interpretação de textos', 'medio', '"A testemunha foi considerada inidônea pelo juiz."<br><br>O adjetivo "inidônea" atribui à testemunha a característica de:', 'Especialista no assunto.', 'Pessoa de moral duvidosa, não confiável.', 'Pessoa muito idosa.', 'Pessoa com deficiência auditiva.', 'b', 'Inidôneo (o contrário de idôneo) é aquele que não tem moral ilibada, que não é apto ou de confiança.'),
('lingua-portuguesa', 'Interpretação de textos', 'medio', '"Por conseguinte, a licitação foi declarada deserta."<br><br>A expressão "Por conseguinte" equivale a:', 'Em contrapartida.', 'Sendo assim (conclusão).', 'Por causa de.', 'Para que.', 'b', '"Por conseguinte" é uma locução conjuntiva conclusiva, sinônimo de "logo", "portanto", "sendo assim".'),

-- ==================== FASE 3: DIFÍCIL (10 Questões) ====================
('lingua-portuguesa', 'Interpretação de textos', 'dificil', 'Em "A retórica do candidato, eivada de falácias, não convenceu os presentes", a expressão "eivada de" significa:', 'Vazia de', 'Repleta de, contaminada por', 'Protegida por', 'Esclarecida por', 'b', '"Eivado" significa contaminado, infectado, cheio de algo (geralmente negativo).'),
('lingua-portuguesa', 'Interpretação de textos', 'dificil', 'Leia: "O juiz exarou a sentença de forma peremptória."<br><br>O termo "peremptória" indica que a decisão foi:', 'Provisória e sujeita a muitas mudanças.', 'Terminante, definitiva, que não admite contestação.', 'Confusa e de difícil interpretação.', 'Rápida, porém incompleta.', 'b', 'Peremptório é aquilo que é decisivo, categórico, que põe fim imediato a algo, não admitindo hesitação.'),
('lingua-portuguesa', 'Interpretação de textos', 'dificil', '"A medida governamental teve um efeito paliativo na crise."<br><br>Isso significa que a medida:', 'Resolveu o problema pela raiz.', 'Piorou drasticamente a situação.', 'Atenuou o problema temporariamente, sem resolvê-lo.', 'Foi ignorada pela população.', 'c', 'Paliativo é aquilo que serve apenas para aliviar ou atenuar temporariamente um mal, sem curá-lo ou resolvê-lo.'),
('lingua-portuguesa', 'Interpretação de textos', 'dificil', '"O réu agiu de forma furtiva durante o interrogatório."<br><br>"Furtiva" pode ser corretamente substituído por:', 'Agressiva e violenta.', 'Colaborativa e sincera.', 'Dissimulada e sorrateira.', 'Lenta e sonolenta.', 'c', 'Furtivo refere-se àquilo que é feito às escondidas, de forma sorrateira ou dissimulada.'),
('lingua-portuguesa', 'Interpretação de textos', 'dificil', '"O acordo foi tacitamente aceito por ambas as partes."<br><br>O advérbio "tacitamente" implica que a aceitação foi:', 'Feita através de um contrato escrito e assinado.', 'Feita em voz alta diante de testemunhas.', 'Subentendida, sem necessidade de palavras expressas.', 'Recusada após longo debate.', 'c', 'Tácito é o que não é expresso formalmente ou por palavras, mas que está implícito ou subentendido.'),
('lingua-portuguesa', 'Interpretação de textos', 'dificil', '"Comportamento pusilânime não é tolerado nesta corporação."<br><br>Uma pessoa pusilânime é aquela que é:', 'Extremamente corajosa.', 'Covarde, fraca de ânimo.', 'Muito inteligente e astuta.', 'Rebelde e questionadora.', 'b', 'Pusilânime é um adjetivo para alguém que demonstra covardia, fraqueza de caráter ou falta de ânimo.'),
('lingua-portuguesa', 'Interpretação de textos', 'dificil', 'No trecho: "O projeto peca pela sua prolixidade", o autor critica o fato de o projeto ser:', 'Muito curto e sem detalhes importantes.', 'Excessivamente longo e com palavras desnecessárias.', 'Inovador demais para a época.', 'Plagiado de outros autores.', 'b', 'Prolixidade (ser prolixo) é o excesso de palavras para explicar algo simples, falta de concisão.'),
('lingua-portuguesa', 'Interpretação de textos', 'dificil', 'Considere: "As acusações contra o gestor eram inócuas."<br><br>Isso significa que as acusações eram:', 'Muito graves e com provas irrefutáveis.', 'Inofensivas, que não causam dano ou prejuízo.', 'Feitas por pessoas anônimas.', 'Enviadas ao tribunal de justiça.', 'b', 'Inócuo é aquilo que não faz mal, que é inofensivo ou que não produz efeito.'),
('lingua-portuguesa', 'Interpretação de textos', 'dificil', '"Na epígrafe do seu livro, o autor resumiu sua filosofia de vida."<br><br>O que é uma "epígrafe"?', 'O último capítulo que conclui a história.', 'Uma dedicatória aos pais.', 'Uma pequena citação no início do livro ou capítulo.', 'O índice ou sumário da obra.', 'c', 'Epígrafe é uma citação curta colocada no começo de uma obra ou capítulo, servindo de tema para o que será escrito.'),
('lingua-portuguesa', 'Interpretação de textos', 'dificil', '"Não devemos agir com leviandade em assuntos de tamanha envergadura."<br><br>"Leviandade" e "envergadura" significam, respectivamente:', 'Seriedade / tamanho', 'Irresponsabilidade / importância', 'Lentidão / dificuldade', 'Velocidade / peso', 'b', 'Leviandade é falta de reflexão, irresponsabilidade (agir de forma leviana). Envergadura, no contexto, significa importância, grandeza.');
