-- =============================================================================
-- GABARITA — 30 Questões Reais/Adaptadas (Alto Nível / Estilo COTEC)
-- Fases: 10 Fáceis, 10 Médias, 10 Difíceis
-- =============================================================================

-- 1. LIMPEZA TOTAL DA DISCIPLINA PARA EVITAR REPETIÇÃO
DELETE FROM public.questions WHERE disciplina = 'lingua-portuguesa' AND topico = 'Interpretação de textos';

-- 2. INSERÇÃO DAS NOVAS QUESTÕES
insert into public.questions (disciplina, topico, nivel_dificuldade, enunciado, opcao_a, opcao_b, opcao_c, opcao_d, gabarito, explicacao) values

-- ==================== FASE 1: FÁCIL (10 Questões) ====================

('lingua-portuguesa', 'Interpretação de textos', 'facil', '<strong>Texto I</strong><br>A administração pública direta e indireta de qualquer dos Poderes da União, dos Estados, do Distrito Federal e dos Municípios obedecerá aos princípios de legalidade, impessoalidade, moralidade, publicidade e eficiência. (Art. 37, CF/88).<br><br>De acordo com a leitura do Texto I, é correto afirmar que os princípios citados devem ser obedecidos:', 'Apenas pela administração pública indireta da União.', 'Somente pelos Municípios e pelo Distrito Federal.', 'Pela administração direta e indireta de todos os entes federativos.', 'Apenas pelo Poder Executivo dos Estados.', 'c', 'Compreensão explícita. O texto afirma claramente que a administração direta e indireta de "qualquer dos Poderes da União, dos Estados, do Distrito Federal e dos Municípios" deve obedecer aos princípios.'),

('lingua-portuguesa', 'Interpretação de textos', 'facil', '<strong>Texto I</strong><br>A administração pública direta e indireta de qualquer dos Poderes da União, dos Estados, do Distrito Federal e dos Municípios obedecerá aos princípios de legalidade, impessoalidade, moralidade, publicidade e eficiência.<br><br>A palavra "obedecerá" (segunda linha) indica uma ação que:', 'Já ocorreu no passado.', 'Pode ou não ocorrer, sendo facultativa.', 'Ocorrerá no futuro, com sentido de obrigatoriedade.', 'Está ocorrendo no momento da fala.', 'c', 'O verbo "obedecerá" está no futuro do presente do indicativo, e no jargão jurídico/administrativo, impõe uma norma/obrigação a ser cumprida.'),

('lingua-portuguesa', 'Interpretação de textos', 'facil', '<strong>Texto II</strong><br>A sustentabilidade deixou de ser apenas uma palavra da moda para se tornar uma necessidade urgente. Se não mudarmos nossos hábitos de consumo hoje, as próximas gerações herdarão um planeta esgotado.<br><br>Qual é o tema central do Texto II?', 'O surgimento de novas palavras na moda.', 'A importância urgente de adotar práticas sustentáveis.', 'O aumento do consumo das próximas gerações.', 'O esgotamento financeiro do planeta.', 'b', 'O texto foca na transformação da "sustentabilidade" de uma moda para uma necessidade vital (urgente) visando poupar o planeta.'),

('lingua-portuguesa', 'Interpretação de textos', 'facil', '<strong>Texto II</strong><br>A sustentabilidade deixou de ser apenas uma palavra da moda para se tornar uma necessidade urgente. Se não mudarmos nossos hábitos de consumo hoje, as próximas gerações herdarão um planeta esgotado.<br><br>No trecho "Se não mudarmos nossos hábitos", a conjunção "Se" expressa uma ideia de:', 'Causa', 'Consequência', 'Condição', 'Adição', 'c', 'A conjunção "Se" é condicional, indicando que a mudança de hábitos é a condição para que as próximas gerações não herdem um planeta esgotado.'),

('lingua-portuguesa', 'Interpretação de textos', 'facil', '<strong>Texto III</strong><br>O silêncio na sala de reuniões era tão denso que podia ser cortado com uma faca. O gerente olhou para os relatórios e suspirou, sabendo que os cortes orçamentários seriam drásticos.<br><br>O que se pode afirmar sobre o ambiente descrito no Texto III?', 'Havia um clima de tensão e apreensão.', 'Havia um clima de festa e celebração.', 'As pessoas estavam conversando em voz muito alta.', 'O gerente estava aliviado com os resultados.', 'a', 'A expressão "silêncio tão denso que podia ser cortado com uma faca" e o suspiro do gerente diante de cortes indicam forte tensão.'),

('lingua-portuguesa', 'Interpretação de textos', 'facil', '<strong>Texto III</strong><br>O silêncio na sala de reuniões era tão denso que podia ser cortado com uma faca.<br><br>Nesse trecho, o autor utiliza qual figura de linguagem para exagerar a densidade do silêncio?', 'Pleonasmo', 'Metáfora', 'Eufemismo', 'Hipérbole', 'd', 'A Hipérbole é a figura do exagero. Dizer que o silêncio "podia ser cortado com uma faca" é um exagero intencional para expressar a tensão.'),

('lingua-portuguesa', 'Interpretação de textos', 'facil', '<strong>Texto IV - Charge (Descrição)</strong><br>Um homem está diante de uma árvore cortada, segurando um machado. Ao lado, uma placa diz: "Preserve a natureza". Ele olha para a placa e diz: "Faltou papel para imprimir mais dessas".<br><br>O humor da charge decorre principalmente da:', 'Beleza do desenho da árvore.', 'Contradição entre a ação do homem e a mensagem da placa.', 'Falta de papel nas gráficas modernas.', 'Habilidade do lenhador no uso do machado.', 'b', 'O humor crítico da charge reside na ironia e contradição: o homem destrói a árvore (natureza) para fazer papel que será usado para imprimir placas pedindo preservação.'),

('lingua-portuguesa', 'Interpretação de textos', 'facil', '<strong>Texto V</strong><br>Art. 5º Todos são iguais perante a lei, sem distinção de qualquer natureza, garantindo-se aos brasileiros e aos estrangeiros residentes no País a inviolabilidade do direito à vida, à liberdade, à igualdade, à segurança e à propriedade.<br><br>De acordo com o texto, o direito à igualdade é garantido a:', 'Apenas aos brasileiros natos.', 'Apenas aos estrangeiros que visitam o País.', 'Brasileiros e estrangeiros residentes no País.', 'Apenas às autoridades governamentais.', 'c', 'Interpretação direta. O texto é claro ao dizer: "garantindo-se aos brasileiros e aos estrangeiros residentes no País".'),

('lingua-portuguesa', 'Interpretação de textos', 'facil', '<strong>Texto VI</strong><br>Foi aprovada a nova lei municipal que prevê multas pesadas para quem descartar lixo em terrenos baldios. A medida entra em vigor na próxima segunda-feira.<br><br>O texto acima pertence a qual gênero textual, dado seu caráter informativo e direto?', 'Notícia', 'Poema', 'Crônica poética', 'Receita culinária', 'a', 'O texto tem o objetivo claro e direto de informar sobre um fato recente (aprovação de lei), característica primordial da notícia.'),

('lingua-portuguesa', 'Interpretação de textos', 'facil', '<strong>Texto VI</strong><br>Foi aprovada a nova lei municipal que prevê multas pesadas para quem descartar lixo em terrenos baldios. A medida entra em vigor na próxima segunda-feira.<br><br>No texto, a expressão "A medida" refere-se a:', 'Ao lixo descartado.', 'Aos terrenos baldios.', 'À nova lei municipal aprovada.', 'À segunda-feira.', 'c', '"A medida" atua como elemento coesivo anafórico, retomando a "nova lei municipal" citada na frase anterior para evitar repetição.'),


-- ==================== FASE 2: MÉDIO (10 Questões) ====================

('lingua-portuguesa', 'Interpretação de textos', 'medio', '<strong>Texto VII</strong><br>"O progresso tecnológico, malgrado os inegáveis benefícios que trouxe à medicina moderna, suscitou dilemas éticos de difícil resolução. Médicos e cientistas veem-se, cotidianamente, divididos entre a possibilidade técnica e a moralidade da ação."<br><br>No texto, o conectivo "malgrado" pode ser substituído, sem alteração de sentido, por:', 'Por conseguinte', 'Embora', 'Por causa de', 'À medida que', 'b', 'A palavra "malgrado" é uma conjunção ou locução prepositiva concessiva, possuindo o mesmo valor semântico de "embora", "apesar de", "conquanto". (Perfil clássico da COTEC).'),

('lingua-portuguesa', 'Interpretação de textos', 'medio', '<strong>Texto VII</strong><br>"Médicos e cientistas veem-se, cotidianamente, divididos entre a possibilidade técnica e a moralidade da ação."<br><br>O pronome "se", na forma "veem-se", exerce a função de:', 'Índice de indeterminação do sujeito.', 'Partícula apassivadora.', 'Pronome reflexivo, indicando que a ação recai sobre os próprios sujeitos.', 'Conjunção subordinativa condicional.', 'c', 'Eles "veem a si mesmos" (ou uns aos outros) divididos. O "se" é reflexivo, retomando os sujeitos "Médicos e cientistas".'),

('lingua-portuguesa', 'Interpretação de textos', 'medio', '<strong>Texto VIII</strong><br>"No Brasil, a leitura ainda é vista por muitos como uma obrigação escolar, e não como um deleite. Destarte, as políticas públicas de incentivo devem focar não apenas na distribuição de livros, mas na formação de mediadores literários."<br><br>O termo "Destarte" foi empregado no texto para introduzir uma:', 'Ideia de oposição ao que foi dito antes.', 'Conclusão derivada do raciocínio anterior.', 'Adição de uma informação irrelevante.', 'Concessão a um argumento contrário.', 'b', '"Destarte" (assim, dessa forma, por conseguinte) é um conectivo conclusivo. A COTEC adora testar o vocabulário de conectivos eruditos.'),

('lingua-portuguesa', 'Interpretação de textos', 'medio', '<strong>Texto VIII</strong><br>"No Brasil, a leitura ainda é vista por muitos como uma obrigação escolar, e não como um deleite."<br><br>Segundo o trecho, a palavra "deleite" pode ser entendida, no contexto, como antônimo de:', 'Castigo', 'Prazer', 'Livro', 'Formação', 'a', 'Se a leitura é vista como "obrigação" (peso/castigo) e NÃO como "deleite", "deleite" significa prazer, satisfação. Como a questão pede o ANTÔNIMO de deleite no contexto de obrigação, a palavra mais próxima da oposição (obrigação/peso) seria castigo/sofrimento. (Gabarito A: Antônimo de deleite = Castigo/Obrigação pesada. Prazer é sinônimo).'),

('lingua-portuguesa', 'Interpretação de textos', 'medio', '<strong>Texto IX</strong><br>"A cidade acordou cinzenta e triste. Os prédios pareciam chorar com a chuva fina que caía desde a madrugada, lavando as calçadas sujas da metrópole."<br><br>A atribuição de sentimentos humanos (triste, chorar) à cidade e aos prédios configura a figura de linguagem denominada:', 'Metonímia', 'Prosopopeia (Personificação)', 'Antítese', 'Catacrese', 'b', 'A Prosopopeia ou Personificação é a figura que atribui características humanas a seres inanimados ou irracionais (cidade triste, prédios choram).'),

('lingua-portuguesa', 'Interpretação de textos', 'medio', '<strong>Texto X</strong><br>"Fui à repartição cobrar meus direitos. Lá chegando, deparei-me com uma fila quilométrica e um atendente que trabalhava a passo de tartaruga."<br><br>A expressão "passo de tartaruga" constitui um exemplo de linguagem:', 'Estritamente denotativa.', 'Científica e técnica.', 'Conotativa, utilizada para indicar extrema lentidão.', 'Formal, típica de documentos oficiais.', 'c', 'O uso não literal das palavras caracteriza a conotação. "Passo de tartaruga" é uma metáfora cristalizada para lentidão.'),

('lingua-portuguesa', 'Interpretação de textos', 'medio', '<strong>Texto XI</strong><br>"A educação de qualidade é a mola propulsora de uma nação. Sem ela, o país patina, estagna e retrocede."<br><br>Sobre a organização coesiva do trecho, a palavra "ela" substitui:', 'A nação.', 'A mola propulsora.', 'A educação de qualidade.', 'A estagnação.', 'c', 'O pronome pessoal "ela" atua como termo anafórico, retomando o sujeito principal da oração anterior: "A educação de qualidade".'),

('lingua-portuguesa', 'Interpretação de textos', 'medio', '<strong>Texto XII</strong><br>"O servidor público, no exercício de suas funções, não pode abrir mão da ética. Outrossim, deve primar pela eficiência para garantir o bem comum."<br><br>A palavra "Outrossim" tem o papel de:', 'Contrapor a ética à eficiência.', 'Adicionar um novo dever ao servidor (além de, igualmente).', 'Explicar a causa da falta de eficiência.', 'Concluir que a ética é desnecessária.', 'b', '"Outrossim" é um conectivo de adição. Significa "igualmente", "também", "do mesmo modo".'),

('lingua-portuguesa', 'Interpretação de textos', 'medio', '<strong>Texto XIII</strong><br>"A corrupção é um câncer que corrói as estruturas do Estado democrático."<br><br>O emprego da palavra "câncer" no texto tem a intenção de:', 'Fornecer um diagnóstico médico ao Estado.', 'Enfatizar o caráter destrutivo e disseminador da corrupção na sociedade.', 'Elogiar a resiliência das estruturas do Estado democrático.', 'Propor um tratamento hospitalar aos políticos.', 'b', 'Trata-se de uma metáfora para ilustrar o quanto a corrupção é nociva, espalhando-se e destruindo as bases do Estado, assim como a doença destrói o corpo.'),

('lingua-portuguesa', 'Interpretação de textos', 'medio', '<strong>Texto XIV</strong><br>"Ele fala muito, contudo age pouco na hora de resolver os problemas do setor."<br><br>A conjunção "contudo" expressa o mesmo sentido que a palavra:', 'Portanto', 'Todavia', 'Porquanto', 'Conforme', 'b', '"Contudo" é conjunção adversativa, assim como "mas", "porém", "todavia", "entretanto", expressando oposição ou ressalva.'),


-- ==================== FASE 3: DIFÍCIL (10 Questões) ====================

('lingua-portuguesa', 'Interpretação de textos', 'dificil', '<strong>Texto XV</strong><br>"O esvaziamento das políticas culturais não é um fenômeno fortuito. Pelo contrário, revela uma idiossincrasia de gestões que percebem o pensamento crítico como uma ameaça velada à hegemonia do poder vigente."<br><br>O vocábulo "idiossincrasia", no contexto do texto, refere-se a:', 'Um comportamento padrão e universal de qualquer governo.', 'Uma característica peculiar, traço próprio ou modo de agir específico dessas gestões.', 'Uma lei federal que proíbe o financiamento cultural.', 'Um erro de cálculo orçamentário.', 'b', 'A COTEC exige amplo repertório vocabular. Idiossincrasia significa maneira de ver, sentir e reagir peculiar a cada indivíduo ou grupo; um traço de comportamento específico.'),

('lingua-portuguesa', 'Interpretação de textos', 'dificil', '<strong>Texto XV</strong><br>"O esvaziamento das políticas culturais não é um fenômeno fortuito. Pelo contrário, revela uma idiossincrasia de gestões..."<br><br>A palavra "fortuito" pode ser substituída, sem prejuízo de sentido, por:', 'Acidental ou casual.', 'Planejado e estruturado.', 'Violento e agressivo.', 'Ilegal e criminoso.', 'a', 'Fortuito significa aquilo que acontece por acaso, de maneira imprevista. O autor afirma que NÃO é fortuito, ou seja, é intencional.'),

('lingua-portuguesa', 'Interpretação de textos', 'dificil', '<strong>Texto XVI</strong><br>"A inércia burocrática é a verdadeira nêmesis da inovação. Enquanto o mundo digital orbita na velocidade da luz, as repartições engatinham amarradas a processos anacrônicos."<br><br>A partir da leitura, infere-se que o autor considera os processos das repartições como:', 'Modernos, porém incompreendidos pela sociedade.', 'Desatualizados e incompatíveis com a época atual (obsoletos).', 'Necessários para evitar o excesso de velocidade digital.', 'Divertidos, como uma criança que engatinha.', 'b', 'A palavra chave é "anacrônicos", que significa aquilo que contraria a cronologia, que está fora de época, antiquado, obsoleto.'),

('lingua-portuguesa', 'Interpretação de textos', 'dificil', '<strong>Texto XVII</strong><br>"As decisões do STF têm caráter erga omnes nos casos de controle concentrado de constitucionalidade, vinculando os demais órgãos judiciários."<br><br>A expressão latina "erga omnes" no jargão jurídico-administrativo significa:', 'Que se aplica apenas às partes envolvidas no processo.', 'Que vale para todos, atingindo terceiros de forma geral.', 'Que não tem validade até que o Presidente aprove.', 'Que se refere a erros cometidos pelos magistrados.', 'b', '"Erga omnes" é expressão amplamente cobrada em concursos de nível superior/médio especializado, significando "contra todos" ou "vale para todos".'),

('lingua-portuguesa', 'Interpretação de textos', 'dificil', '<strong>Texto XVIII</strong><br>"Choveu a cântaros durante a eleição, de sorte que o comparecimento às urnas foi pífio em diversas zonas rurais."<br><br>A locução "de sorte que" introduz, na oração, um valor semântico de:', 'Explicação do motivo da chuva.', 'Concessão, indicando que as urnas estavam cheias apesar da chuva.', 'Consequência da chuva intensa sobre o comparecimento.', 'Comparação entre a chuva e as urnas.', 'c', 'A locução "de sorte que" (assim como "de modo que") é consecutiva, ou seja, expressa a consequência do que foi relatado antes.'),

('lingua-portuguesa', 'Interpretação de textos', 'dificil', '<strong>Texto XIX</strong><br>"Posto que a situação financeira do município fosse precária, o prefeito não hesitou em aprovar a licitação para a obra do estádio."<br><br>No texto, a locução "Posto que" pode causar dúvida, mas no padrão normativo cobrado em provas, ela expressa:', 'Causa (Por causa de)', 'Conclusão (Portanto)', 'Concessão (Embora / Mesmo que)', 'Tempo (Logo que)', 'c', 'Embora no dia a dia as pessoas usem "posto que" como causal ("já que"), a norma culta e as bancas (como a COTEC) a consideram uma conjunção estritamente CONCESSIVA (equivale a embora, ainda que). É a maior pegadinha da gramática.'),

('lingua-portuguesa', 'Interpretação de textos', 'dificil', '<strong>Texto XX</strong><br>"O depoimento do réu foi considerado inverossímil, repleto de digressões que tentavam confundir o magistrado."<br><br>As palavras "inverossímil" e "digressões" significam, respectivamente:', 'Verdadeiro / detalhes precisos.', 'Não merecedor de crédito (improvável) / desvios do assunto principal.', 'Agressivo / xingamentos.', 'Comovente / lágrimas e prantos.', 'b', 'Inverossímil é aquilo que não parece verdadeiro, improvável. Digressão é o ato de afastar-se do assunto principal, enrolar, divagar.'),

('lingua-portuguesa', 'Interpretação de textos', 'dificil', '<strong>Texto XXI</strong><br>"No discurso, o líder sindical ratificou as críticas à diretoria, mas retificou os dados salariais apresentados na semana anterior."<br><br>Qual a relação de sentido entre "ratificou" e "retificou" na frase?', 'Ele apagou as críticas e confirmou os dados.', 'Ele confirmou as críticas e corrigiu os dados.', 'Ele questionou as críticas e ocultou os dados.', 'Ele elogiou as críticas e piorou os dados.', 'b', 'Ratificar é confirmar, reafirmar. Retificar é corrigir, emendar. Trata-se de uma questão clássica de parônimos muito cobrada pela COTEC.'),

('lingua-portuguesa', 'Interpretação de textos', 'dificil', '<strong>Texto XXII</strong><br>"Para eximir-se da responsabilidade, o servidor alegou desconhecimento da norma processual."<br><br>O verbo "eximir-se" tem o sentido de:', 'Punir-se voluntariamente.', 'Isentar-se, livrar-se de uma obrigação ou culpa.', 'Assumir corajosamente a falha.', 'Candidatar-se a um cargo superior.', 'b', 'Eximir-se é o ato de tentar ficar livre de um dever, obrigação ou responsabilidade; isentar-se.'),

('lingua-portuguesa', 'Interpretação de textos', 'dificil', '<strong>Texto XXIII</strong><br>"A decisão do tribunal foi considerada draconiana pelos advogados de defesa, que apelaram imediatamente."<br><br>O adjetivo "draconiana" é usado para qualificar uma decisão que é:', 'Muito justa e equilibrada.', 'Extremamente severa, rigorosa e impiedosa.', 'Baseada na lei dos dragões da ficção.', 'Rápida e eficaz.', 'b', 'O termo "draconiano" deriva do legislador grego Drácon, conhecido por suas leis extremamente severas. O termo é muito usado no jargão jurídico para denotar rigor excessivo.');
