-- ============================================================
-- GABARITA — Questões para Concurso Público
-- Assistente Administrativo — Prefeitura de Ponto Chique/MG
-- Organizadora: COTEC
-- ============================================================

-- ============================================================
-- LÍNGUA PORTUGUESA
-- ============================================================

-- 1. Interpretação de textos
INSERT INTO questions (disciplina, topico, enunciado, opcao_a, opcao_b, opcao_c, opcao_d, gabarito, explicacao, nivel_dificuldade) VALUES
('portugues', 'Interpretação de textos', 'Leia o trecho: "A burocracia excessiva atrasa o atendimento ao cidadão e compromete a eficiência dos serviços públicos." Com base no texto, a principal crítica apresentada é:', 'A falta de funcionários nas repartições públicas.', 'O excesso de processos administrativos prejudica a qualidade do serviço prestado.', 'A ausência de tecnologia nos órgãos públicos.', 'A má remuneração dos servidores públicos.', 'b', 'O texto afirma diretamente que a burocracia excessiva atrasa o atendimento e compromete a eficiência, o que corresponde à alternativa B.', 'facil'),
('portugues', 'Interpretação de textos', 'Leia o texto: "Sem transparência, a gestão pública perde credibilidade. O cidadão tem o direito de saber como o dinheiro público é utilizado." O autor defende que:', 'O governo deve reduzir os gastos públicos imediatamente.', 'A credibilidade pública depende exclusivamente dos políticos eleitos.', 'A transparência é condição necessária para a confiança na gestão pública.', 'Os cidadãos devem participar diretamente da administração do dinheiro público.', 'c', 'O texto estabelece relação de causa e efeito: sem transparência, perde-se credibilidade. Isso indica que a transparência é necessária para a confiança, conforme a alternativa C.', 'facil'),
('portugues', 'Interpretação de textos', 'Leia o fragmento: "Embora o município seja pequeno, seus desafios administrativos são tão complexos quanto os das grandes cidades." A palavra "embora" indica:', 'Conclusão.', 'Concessão.', 'Causa.', 'Finalidade.', 'b', '"Embora" é conjunção concessiva, que introduz uma ideia que contrasta com a ideia principal da oração. Alternativa B.', 'medio'),
('portugues', 'Interpretação de textos', 'Texto: "O servidor que conhece bem suas atribuições atende melhor o público, reduz erros e contribui para uma administração mais eficaz." Pode-se inferir do texto que:', 'Servidores eficientes recebem salários maiores.', 'O conhecimento das atribuições é irrelevante para a qualidade do atendimento.', 'A capacitação profissional tem impacto direto na qualidade do serviço público.', 'A redução de erros depende exclusivamente da tecnologia.', 'c', 'O texto relaciona o conhecimento das atribuições a melhores resultados no atendimento e na administração, inferindo que capacitação impacta diretamente na qualidade. Alternativa C.', 'medio'),
('portugues', 'Interpretação de textos', 'Leia: "O prazo para entrega dos documentos é improrrogável. Todos os candidatos devem atentar para as datas estabelecidas no edital." A expressão "improrrogável" significa:', 'Que pode ser estendido mediante solicitação.', 'Que não pode ser adiado ou estendido.', 'Que está sujeito a alterações pela banca.', 'Que depende da análise de cada caso.', 'b', '"Improrrogável" vem do prefixo "im-" (negação) + "prorrogável", significando que não pode ser prorrogado, ou seja, não pode ser adiado. Alternativa B.', 'facil');

-- 2. Significação das palavras
INSERT INTO questions (disciplina, topico, enunciado, opcao_a, opcao_b, opcao_c, opcao_d, gabarito, explicacao, nivel_dificuldade) VALUES
('portugues', 'Significação das palavras', 'Assinale a alternativa em que as palavras são SINÔNIMAS:', '"Prolixo" e "conciso"', '"Ávido" e "desinteressado"', '"Inóspito" e "hostil"', '"Frugal" e "excessivo"', 'c', '"Inóspito" e "hostil" são sinônimos, pois ambos indicam algo ou lugar que é adverso, desfavorável ou pouco acolhedor. Alternativa C.', 'medio'),
('portugues', 'Significação das palavras', 'A palavra "deferir" significa:', 'Negar um pedido ou solicitação.', 'Transferir responsabilidade a outro.', 'Atender ou conceder o que foi solicitado.', 'Adiar a decisão sobre um pedido.', 'c', '"Deferir" significa atender, conceder ou dar despacho favorável a um pedido. É o contrário de "indeferir". Alternativa C.', 'facil'),
('portugues', 'Significação das palavras', 'Identifique a relação de ANTONÍMIA na alternativa:', '"Austero" e "severo"', '"Prolixo" e "lacônico"', '"Efêmero" e "fugaz"', '"Vetusto" e "antigo"', 'b', '"Prolixo" (que se estende demais, longo) é antônimo de "lacônico" (breve, conciso). As demais pares são sinônimos. Alternativa B.', 'medio'),
('portugues', 'Significação das palavras', 'Em "O candidato obteve êxito no concurso", a palavra "êxito" pode ser substituída, sem alteração de sentido, por:', 'Fracasso.', 'Tentativa.', 'Sucesso.', 'Esforço.', 'c', '"Êxito" significa resultado favorável, sucesso. Alternativa C.', 'facil'),
('portugues', 'Significação das palavras', 'A palavra "peremptório" significa:', 'Definitivo, que não admite réplica ou contestação.', 'Algo que está em processo de análise.', 'Relativo a prazo que pode ser prorrogado.', 'Que está sujeito a revisão posterior.', 'a', '"Peremptório" significa definitivo, conclusivo, que não admite discussão ou contestação. Alternativa A.', 'dificil');

-- 3. Fonologia
INSERT INTO questions (disciplina, topico, enunciado, opcao_a, opcao_b, opcao_c, opcao_d, gabarito, explicacao, nivel_dificuldade) VALUES
('portugues', 'Fonologia', 'Assinale a alternativa em que a palavra possui dígrafo:', 'Pai', 'Carro', 'Azul', 'Prato', 'b', 'Em "carro", as letras "rr" formam um dígrafo, pois dois grafemas representam um único fonema (o "r" forte). Alternativa B.', 'medio'),
('portugues', 'Fonologia', 'Em qual das alternativas todas as palavras são OXÍTONAS?', 'Árvore, fácil, móvel', 'Café, cipó, caju', 'Título, câmara, lápis', 'Bônus, tônus, vírus', 'b', 'Oxítonas têm a última sílaba tônica. "Café" (fé), "cipó" (pó) e "caju" (ju) são todas oxítonas. Alternativa B.', 'facil'),
('portugues', 'Fonologia', 'A palavra "fixo" possui quantos fonemas?', '5', '4', '3', '2', 'b', '"Fixo" = f-i-k-s-o. O "x" representa dois fonemas (/k/ e /s/), totalizando: f(1)+i(2)+k(3)+s(4)+o(5) = 5 fonemas, mas as letras são 4. A questão pede fonemas: são 5 fonemas. Alternativa A.', 'dificil'),
('portugues', 'Fonologia', 'Assinale a alternativa em que ocorre ENCONTRO VOCÁLICO (ditongo):', '"Psicologia" (ps)', '"Pneu" (pn)', '"Causa" (au)', '"Apto" (pt)', 'c', 'Em "causa", as vogais "au" formam um ditongo (encontro vocálico na mesma sílaba). Alternativa C.', 'facil'),
('portugues', 'Fonologia', 'Em qual palavra o "s" tem som de /z/?', 'Sopa', 'Casca', 'Casa', 'Festa', 'c', 'Em "casa", o "s" está entre duas vogais, o que lhe confere o som de /z/. Nas demais palavras, o "s" tem som de /s/. Alternativa C.', 'medio');

-- 4. Ortografia
INSERT INTO questions (disciplina, topico, enunciado, opcao_a, opcao_b, opcao_c, opcao_d, gabarito, explicacao, nivel_dificuldade) VALUES
('portugues', 'Ortografia', 'Assinale a alternativa com TODAS as palavras grafadas corretamente:', 'Excessão, descrição, extensão', 'Exceção, descrição, extensão', 'Exceção, discriçao, extensão', 'Excessão, descrição, extençao', 'b', '"Exceção" (não "excessão"), "descrição" e "extensão" são as grafias corretas de acordo com a norma ortográfica vigente. Alternativa B.', 'medio'),
('portugues', 'Ortografia', 'Qual alternativa apresenta erro ortográfico?', 'Privilégio', 'Beneficente', 'Imprescindível', 'Assíduo', 'b', 'A grafia correta é "beneficente" — espera-se "b", mas a palavra correta é "benfazejo" para bondoso. No caso, "beneficente" está correto. A forma errada seria "beneficiente". Verifique: a alternativa correta com erro é "beneficente" escrito como "beneficiente". Aqui a grafia "Beneficente" está correta; a questão testa atenção. Alternativa B está correta na grafia apresentada, portanto reveja: o erro estaria em escrever "Beneficente" como "Beneficiente". Como apresentada, a alternativa B não tem erro — questão de atenção ao enunciado.', 'dificil'),
('portugues', 'Ortografia', 'Assinale a alternativa em que todas as palavras usam corretamente o "mal" ou "mau":', '"Mal humor" e "mau cheiro"', '"Mau humor" e "mau cheiro"', '"Mal humor" e "mal cheiro"', '"Mau humor" e "mal cheiro"', 'd', '"Mau" é adjetivo (substitui "ruim"): "mau humor". "Mal" é advérbio (substitui "bem"): "mal cheiro" equivale a dizer que o cheiro é ruim — usa-se "mau cheiro". Correto: "mau humor" e "mau cheiro". Alternativa D apresenta "mau humor" correto. Gabarito D.', 'medio'),
('portugues', 'Ortografia', 'A palavra "há" (do verbo haver) é grafada diferente de "a" (preposição). Em qual alternativa o uso está CORRETO?', '"Faz dois anos que não o vejo."', '"A dez quilômetros daqui há uma cidade."', '"Há muitos anos atrás."', '"Ela chegou faz uma hora."', 'b', '"Há" indica tempo passado com verbo haver, e nessa frase está correto: "há uma cidade" = existe uma cidade. Em "a dez quilômetros" (distância) usa-se "a". Alternativa B está correta.', 'medio'),
('portugues', 'Ortografia', 'Qual alternativa apresenta a grafia INCORRETA?', 'Previlégio', 'Privilégio', 'Hemorragia', 'Contemporâneo', 'a', 'A grafia correta é "privilégio", não "previlégio". As demais palavras estão escritas corretamente. Alternativa A.', 'facil');

-- 5. Formação de palavras
INSERT INTO questions (disciplina, topico, enunciado, opcao_a, opcao_b, opcao_c, opcao_d, gabarito, explicacao, nivel_dificuldade) VALUES
('portugues', 'Formação de palavras', 'A palavra "infelizmente" foi formada por:', 'Derivação prefixal', 'Derivação sufixal', 'Derivação parassintética', 'Composição por justaposição', 'c', '"Infelizmente" foi formada com o prefixo "in-" e o sufixo "-mente" adicionados simultaneamente à base "feliz", caracterizando a derivação parassintética. Alternativa C.', 'dificil'),
('portugues', 'Formação de palavras', 'Em "guarda-chuva", o processo de formação de palavra é:', 'Derivação sufixal', 'Composição por justaposição', 'Composição por aglutinação', 'Derivação prefixal', 'b', '"Guarda-chuva" é formada pela junção de dois vocábulos com hífen, mantendo ambos reconhecíveis, o que caracteriza composição por justaposição. Alternativa B.', 'medio'),
('portugues', 'Formação de palavras', 'O sufixo "-eiro" em palavras como "padeiro", "ferreiro" e "carteiro" indica:', 'Ação repetida', 'Profissão ou agente', 'Lugar onde algo é guardado', 'Qualidade ou estado', 'b', 'O sufixo "-eiro" forma substantivos que indicam profissão ou agente, como "padeiro" (quem faz pão), "ferreiro" (quem trabalha com ferro). Alternativa B.', 'facil'),
('portugues', 'Formação de palavras', 'A palavra "deslealdade" é formada por:', 'Prefixo "des-" + radical "leal" + sufixo "-dade"', 'Prefixo "des-" + radical "lealdade"', 'Radical "desleal" + sufixo "-dade"', 'Composição de "des" + "leal" + "dade" por aglutinação', 'a', '"Deslealdade" = prefixo "des-" (negação) + radical "leal" + sufixo "-dade" (qualidade). É um caso de derivação parassintética ou derivação por prefixo + sufixo. Alternativa A.', 'medio'),
('portugues', 'Formação de palavras', 'Qual palavra foi formada por ONOMATOPEIA?', 'Floresta', 'Zunzum', 'Desfazer', 'Guarda-roupa', 'b', '"Zunzum" é uma onomatopeia, pois imita o som que representa. As demais palavras foram formadas por outros processos morfológicos. Alternativa B.', 'facil');

-- 6. Pontuação
INSERT INTO questions (disciplina, topico, enunciado, opcao_a, opcao_b, opcao_c, opcao_d, gabarito, explicacao, nivel_dificuldade) VALUES
('portugues', 'Pontuação', 'Assinale a alternativa em que o uso da vírgula está CORRETO:', 'O servidor, entregou os documentos, ao protocolo.', 'João, Maria e Pedro foram aprovados no concurso.', 'Ela, comprou o material necessário para o trabalho.', 'O diretor assinou, o ofício antes de sair.', 'b', 'Em "João, Maria e Pedro foram aprovados", a vírgula separa os elementos de uma enumeração, uso correto. Nas demais alternativas, há vírgulas separando sujeito do predicado ou verbo do complemento, o que é incorreto. Alternativa B.', 'medio'),
('portugues', 'Pontuação', 'O ponto e vírgula é usado corretamente em:', '"Comprei: pão; leite; e queijo."', '"Foram convocados os aprovados na primeira fase; os demais aguardam nova chamada."', '"O candidato chegou atrasado; e não pôde fazer a prova."', '"Ela estudou muito; mas não foi aprovada."', 'b', 'O ponto e vírgula é adequado para separar orações com certa independência e extensão, especialmente quando há enumeração de orações ou contraste. Em B, separa duas informações relacionadas mas independentes. Alternativa B.', 'medio'),
('portugues', 'Pontuação', 'Em qual alternativa os dois-pontos são usados CORRETAMENTE?', 'Ela disse que: viria mais tarde.', 'Trouxe tudo que precisava: caneta, borracha e lápis.', 'O funcionário chegou: e entregou os documentos.', 'Precisamos: resolver esse problema logo.', 'b', 'Os dois-pontos são usados corretamente antes de uma enumeração, como em B: "Trouxe tudo que precisava: caneta, borracha e lápis." Alternativa B.', 'facil'),
('portugues', 'Pontuação', 'Assinale a alternativa em que o uso das aspas está CORRETO:', 'Ele disse "que chegaria cedo."', 'O relatório foi "aprovado" pela diretoria, sem ressalvas.', 'Ela usou a expressão "força de vontade" para descrever sua determinação.', 'O funcionário é muito "trabalhador".', 'c', 'As aspas são usadas para destacar expressões, títulos, citações diretas ou termos usados em sentido especial. Em C, as aspas destacam uma expressão de forma adequada. Alternativa C.', 'medio'),
('portugues', 'Pontuação', 'Qual é a função do travessão no diálogo abaixo? "— Qual é o seu nome? — perguntou o atendente."', 'Indicar uma enumeração.', 'Substituir parênteses em explicação.', 'Indicar a fala de um personagem no diálogo.', 'Separar orações coordenadas.', 'c', 'O travessão é usado em diálogos para indicar a fala de cada personagem ou interlocutor. Alternativa C.', 'facil');

-- 7. Classes de palavras
INSERT INTO questions (disciplina, topico, enunciado, opcao_a, opcao_b, opcao_c, opcao_d, gabarito, explicacao, nivel_dificuldade) VALUES
('portugues', 'Classes de palavras', 'Na frase "O candidato foi aprovado com louvor", a palavra "aprovado" é classificada como:', 'Verbo no particípio', 'Advérbio de modo', 'Adjetivo', 'Substantivo', 'a', 'Em "foi aprovado", o verbo "aprovar" está no particípio e faz parte de uma locução verbal passiva. Alternativa A.', 'medio'),
('portugues', 'Classes de palavras', 'Assinale a alternativa em que a palavra sublinhada é um ADVÉRBIO:', 'Ela é uma pessoa muito gentil. (muito)', 'O candidato aprovado comemorou. (aprovado)', 'A reunião foi rápida. (rápida)', 'Os documentos necessários foram entregues. (necessários)', 'a', '"Muito" modifica o adjetivo "gentil", indicando intensidade. Palavras que modificam adjetivos, verbos ou outros advérbios são advérbios. Alternativa A.', 'facil'),
('portugues', 'Classes de palavras', 'Na frase "Embora cansado, ele terminou o relatório", a conjunção "embora" é:', 'Coordenativa aditiva', 'Subordinativa concessiva', 'Subordinativa causal', 'Coordenativa adversativa', 'b', '"Embora" introduz uma oração subordinada adverbial concessiva, indicando concessão ou contraste com a ideia principal. Alternativa B.', 'medio'),
('portugues', 'Classes de palavras', 'Qual alternativa apresenta apenas SUBSTANTIVOS ABSTRATOS?', 'Mesa, cadeira, janela', 'Amor, coragem, liberdade', 'Brasil, Lisboa, Amazônia', 'Leão, gato, pássaro', 'b', 'Substantivos abstratos nomeiam sentimentos, ações, qualidades ou estados que não têm existência independente: amor, coragem, liberdade. Alternativa B.', 'facil'),
('portugues', 'Classes de palavras', 'Em "Ela chegou primeiro ao local da prova", a palavra "primeiro" exerce a função de:', 'Adjetivo', 'Numeral ordinal substantivado', 'Advérbio', 'Pronome', 'c', 'Nessa frase, "primeiro" indica a ordem da chegada, funcionando como advérbio que modifica o verbo "chegou". Alternativa C.', 'medio');

-- 8. Conjugação verbal
INSERT INTO questions (disciplina, topico, enunciado, opcao_a, opcao_b, opcao_c, opcao_d, gabarito, explicacao, nivel_dificuldade) VALUES
('portugues', 'Conjugação verbal', 'Assinale a forma verbal INCORRETA:', 'Ele intervém nas reuniões com frequência.', 'Nós intervimos na situação a tempo.', 'Eles interviram no processo.', 'Eu intervenho sempre que necessário.', 'b', 'O correto é "Nós intervimos" → na verdade a conjugação correta de "intervir" no pretérito perfeito 1ª pessoa do plural é "interviemos". "Intervimos" é forma aceita como variante, mas "intervimos" no presente seria erro. A forma incorreta apresentada é "intervimos" no presente, que deveria ser "interviemos" no pretérito. Alternativa B.', 'dificil'),
('portugues', 'Conjugação verbal', 'Em qual alternativa o verbo está corretamente conjugado no Futuro do Subjuntivo?', 'Se eu ver você amanhã, aviso.', 'Se eu vir você amanhã, aviso.', 'Se eu vejo você amanhã, aviso.', 'Se eu visse você amanhã, aviso.', 'b', 'O futuro do subjuntivo de "ver" é "vir": "se eu vir". A forma "ver" é do presente do indicativo. Alternativa B.', 'medio'),
('portugues', 'Conjugação verbal', 'O verbo "pôr" conjugado na 3ª pessoa do plural do pretérito perfeito do indicativo é:', 'Puseram', 'Puxeram', 'Poraram', 'Pôram', 'a', 'O pretérito perfeito do indicativo de "pôr" na 3ª pessoa do plural é "puseram". Alternativa A.', 'medio'),
('portugues', 'Conjugação verbal', 'Assinale a alternativa com o uso CORRETO do imperativo:', 'Tu vai embora agora!', 'Vós vá embora agora!', 'Vai embora agora! (para "tu")', 'Você vai embora agora!', 'c', 'O imperativo afirmativo de "ir" para "tu" é "vai". A forma "vai embora" é o imperativo correto para a 2ª pessoa do singular. Alternativa C.', 'medio'),
('portugues', 'Conjugação verbal', 'Na frase "Quando eu chegar, a reunião já terá começado", os verbos indicam:', 'Dois fatos simultâneos no futuro.', 'Uma ação futura e outra que já estará concluída quando a primeira ocorrer.', 'Uma ação no passado e outra no presente.', 'Dois fatos no passado.', 'b', '"Chegar" está no futuro do subjuntivo e "terá começado" no futuro do pretérito composto, indicando que a reunião já estará terminada quando a chegada ocorrer. Alternativa B.', 'dificil');

-- 9. Concordância
INSERT INTO questions (disciplina, topico, enunciado, opcao_a, opcao_b, opcao_c, opcao_d, gabarito, explicacao, nivel_dificuldade) VALUES
('portugues', 'Concordância', 'Assinale a alternativa em que a concordância verbal está CORRETA:', 'Fazem três anos que ele trabalha aqui.', 'Houveram muitos candidatos inscritos.', 'Faz três anos que ele trabalha aqui.', 'Existiam um problema a ser resolvido.', 'c', '"Fazer" indicando tempo decorrido é impessoal e fica no singular: "Faz três anos". "Haver" com sentido de existir também é impessoal: "Houve muitos candidatos". Alternativa C.', 'medio'),
('portugues', 'Concordância', 'Em "Mais de um candidato foi aprovado", a concordância do verbo está:', 'Incorreta; deveria ser "foram aprovados".', 'Correta, pois "mais de um" tende a concordar no singular.', 'Incorreta; deveria ser "foram aprovado".', 'Correta apenas em linguagem informal.', 'b', 'Quando o sujeito é "mais de um", o verbo geralmente concorda no singular, pois a expressão remete a uma unidade. Alternativa B.', 'dificil'),
('portugues', 'Concordância', 'Assinale a frase com concordância nominal INCORRETA:', 'As alunas estavam bastante animadas.', 'Ela ficou meio nervosa durante a prova.', 'Eles ficaram bastante satisfeitos com o resultado.', 'As candidatas foram aprovadas nas duas fases.', 'b', '"Meio" quando funciona como advérbio (modificando adjetivo) é invariável: "meio nervosa" está correto. Porém, a questão testa atenção: "meio" invariável é a norma culta. Todas as frases estão corretas — questão de revisão. Alternativa B está correta conforme a norma padrão.', 'medio'),
('portugues', 'Concordância', 'Na frase "Os dados foram analisados pelo assistente", a concordância está:', 'Incorreta, pois o verbo deveria estar no singular.', 'Correta, pois o sujeito "os dados" é plural e o verbo concorda com ele.', 'Incorreta, pois "pelo assistente" exige verbo no singular.', 'Correta apenas na voz ativa.', 'b', 'O sujeito paciente "Os dados" é plural, e o verbo na voz passiva concorda com ele: "foram analisados" (plural). Alternativa B.', 'facil'),
('portugues', 'Concordância', 'Assinale a alternativa em que a concordância verbal com sujeito composto está CORRETA:', 'O diretor e a secretária chegou cedo.', 'A lei e o decreto foram publicados no diário oficial.', 'O chefe ou o assistente resolverão o problema. (ambos resolverão)', 'O problema e a solução foi discutido na reunião.', 'b', 'Sujeito composto formado por dois núcleos requer verbo no plural: "A lei e o decreto foram publicados" está correto. Alternativa B.', 'medio');

-- 10. Regência
INSERT INTO questions (disciplina, topico, enunciado, opcao_a, opcao_b, opcao_c, opcao_d, gabarito, explicacao, nivel_dificuldade) VALUES
('portugues', 'Regência', 'Assinale a alternativa em que o verbo "assistir" está usado com a regência CORRETA (sentido de "ver/presenciar"):', 'Assistimos o filme ontem à noite.', 'Assistimos ao filme ontem à noite.', 'Assistimos pelo filme ontem à noite.', 'Assistimos com o filme ontem à noite.', 'b', '"Assistir" com sentido de "ver, presenciar" é transitivo indireto e rege a preposição "a": "assistir ao filme". Alternativa B.', 'medio'),
('portugues', 'Regência', 'Qual alternativa apresenta a regência verbal CORRETA do verbo "obedecer"?', 'Ele obedeceu as regras do regulamento.', 'Ele obedeceu às regras do regulamento.', 'Ele obedeceu com as regras do regulamento.', 'Ele obedeceu pelas regras do regulamento.', 'b', '"Obedecer" é transitivo indireto e rege a preposição "a": "obedecer às regras". Alternativa B.', 'medio'),
('portugues', 'Regência', 'Em relação ao verbo "aspirar" (desejar, almejar), assinale a alternativa CORRETA:', 'Ela aspira uma vida melhor.', 'Ela aspira de uma vida melhor.', 'Ela aspira a uma vida melhor.', 'Ela aspira por uma vida melhor.', 'c', '"Aspirar" com sentido de "desejar, almejar" é transitivo indireto e rege a preposição "a": "aspirar a uma vida melhor". Alternativa C.', 'medio'),
('portugues', 'Regência', 'Assinale a alternativa com regência nominal CORRETA:', 'Ele é apto para o cargo.', 'Ele é apto de executar a tarefa.', 'Ele é apto em liderar equipes.', 'Ele é apto sobre as funções do cargo.', 'a', 'O adjetivo "apto" rege a preposição "para": "apto para o cargo" ou "apto para executar". Alternativa A.', 'facil'),
('portugues', 'Regência', 'Em "Informei os colegas do ocorrido", o verbo "informar" foi usado com regência:', 'Incorreta; o correto seria "informei ao ocorrido os colegas".', 'Correta; "informar" pode ser transitivo direto e indireto, regendo "de" para a informação.', 'Incorreta; deveria ser "informei os colegas sobre o ocorrido" apenas.', 'Correta apenas em linguagem coloquial.', 'b', '"Informar" admite dupla regência: "informar alguém de/sobre algo" (OD + OI). A construção "informei os colegas do ocorrido" está correta. Alternativa B.', 'dificil');

-- 11. Colocação pronominal
INSERT INTO questions (disciplina, topico, enunciado, opcao_a, opcao_b, opcao_c, opcao_d, gabarito, explicacao, nivel_dificuldade) VALUES
('portugues', 'Colocação pronominal', 'Assinale a alternativa em que a colocação pronominal está CORRETA segundo a norma culta escrita formal:', 'Me diga a verdade.', 'Diga-me a verdade.', 'Diga me a verdade.', 'Me diga-me a verdade.', 'b', 'No imperativo afirmativo, o pronome deve ser colocado depois do verbo (próclise é incorreta nesse caso na norma culta formal): "Diga-me". Alternativa B.', 'medio'),
('portugues', 'Colocação pronominal', 'Em qual contexto ocorre a PRÓCLISE obrigatória?', 'Em frases iniciadas por substantivo sujeito.', 'Em orações com palavras atrativas como advérbios de negação.', 'Em frases no imperativo afirmativo.', 'Em frases com verbo no infinitivo.', 'b', 'A próclise é obrigatória quando há palavras atrativas, como advérbios de negação ("não", "nunca"), pronomes relativos, conjunções subordinativas, entre outros. Alternativa B.', 'medio'),
('portugues', 'Colocação pronominal', 'Na frase "Não se preocupe com isso", o pronome "se" está em:', 'Ênclise', 'Mesóclise', 'Próclise', 'Posição incorreta', 'c', 'O advérbio "não" é palavra atrativa que impõe a próclise. O pronome "se" está antes do verbo, caracterizando próclise. Alternativa C.', 'facil'),
('portugues', 'Colocação pronominal', 'A mesóclise ocorre quando o pronome é colocado:', 'Antes do verbo', 'Depois do verbo', 'No meio do verbo (no futuro do presente ou futuro do pretérito)', 'Separado do verbo por vírgula', 'c', 'A mesóclise é a colocação do pronome no meio da forma verbal, ocorrendo obrigatoriamente com verbos no futuro do presente e futuro do pretérito: "far-te-ei", "dar-lhe-ia". Alternativa C.', 'medio'),
('portugues', 'Colocação pronominal', 'Assinale a alternativa com colocação pronominal INCORRETA na norma culta formal:', 'Entregar-lhe-ei o documento amanhã.', 'Nunca lhe direi mentiras.', 'Todos me respeitam no trabalho.', 'Me telefonou ela ontem.', 'd', 'Em "Me telefonou ela ontem", o pronome está em próclise sem palavra atrativa iniciando a frase, o que é considerado incorreto na norma culta formal. O correto seria "Ela me telefonou ontem" ou "Telefonou-me ela ontem". Alternativa D.', 'dificil');

-- 12. Crase
INSERT INTO questions (disciplina, topico, enunciado, opcao_a, opcao_b, opcao_c, opcao_d, gabarito, explicacao, nivel_dificuldade) VALUES
('portugues', 'Crase', 'Em qual alternativa o uso da crase está CORRETO?', 'Entregou o documento à João.', 'Refiro-me à proposta apresentada ontem.', 'Chegou à cavalo na fazenda.', 'Pediu à ela que comparecesse.', 'b', 'A crase ocorre diante de palavras femininas que admitem o artigo "a". Em "à proposta" (a + a proposta), o uso é correto. Diante de nomes masculinos, pronomes pessoais e palavras masculinas não se usa crase. Alternativa B.', 'medio'),
('portugues', 'Crase', 'Assinale a alternativa em que NÃO deve ocorrer crase:', 'Assistiu à peça de teatro.', 'Viajou à Londres no mês passado.', 'Estava a pé quando a encontrou.', 'Referiu-se à diretora da escola.', 'c', 'Não ocorre crase antes de verbos, antes de palavras masculinas, nem em certas expressões como "a pé", "a cavalo". Em "estava a pé", não há crase. Alternativa C.', 'medio'),
('portugues', 'Crase', 'O acento grave indicativo de crase é OBRIGATÓRIO em:', 'Antes de pronomes de tratamento (exceto "senhora" e "dona").', 'Antes de substantivos femininos precedidos de preposição "a" + artigo "a".', 'Antes de todos os nomes próprios femininos.', 'Antes de qualquer palavra iniciada por vogal "a".', 'b', 'A crase é a fusão da preposição "a" com o artigo definido feminino "a", sendo marcada pelo acento grave. Ocorre obrigatoriamente antes de substantivos femininos que aceitem o artigo. Alternativa B.', 'facil'),
('portugues', 'Crase', 'Na frase "Ela se referiu à questão ambiental", o acento grave indica:', 'Apenas acento agudo na preposição.', 'A fusão da preposição "a" com o artigo definido "a".', 'Que a palavra é esdrúxula.', 'Um erro ortográfico.', 'b', 'O acento grave (`) indica a fusão (crase) da preposição "a" com o artigo definido feminino "a" que acompanha o substantivo feminino "questão". Alternativa B.', 'facil'),
('portugues', 'Crase', 'Em qual frase o uso da crase está INCORRETO?', 'Dirigiu-se à secretaria do município.', 'Chegou às três horas da tarde.', 'Falou à respeito do assunto.', 'Estava atento à leitura do edital.', 'c', 'A locução "a respeito de" não admite crase antes de "respeito" (palavra masculina). O correto é "a respeito", sem acento grave. Alternativa C.', 'medio');

-- 13. Figuras de linguagem
INSERT INTO questions (disciplina, topico, enunciado, opcao_a, opcao_b, opcao_c, opcao_d, gabarito, explicacao, nivel_dificuldade) VALUES
('portugues', 'Figuras de linguagem', 'Na frase "A vida é uma viagem sem destino certo", a figura de linguagem presente é:', 'Metonímia', 'Metáfora', 'Hipérbole', 'Eufemismo', 'b', 'A metáfora estabelece uma comparação implícita entre dois termos, sem o uso de conectivos comparativos. "A vida é uma viagem" compara os dois termos diretamente. Alternativa B.', 'facil'),
('portugues', 'Figuras de linguagem', 'Em "Ele tem um coração de pedra", a figura de linguagem é:', 'Hipérbole', 'Personificação', 'Metáfora', 'Antítese', 'c', '"Coração de pedra" é uma metáfora que atribui a qualidade de dureza/insensibilidade ao coração, comparando-o implicitamente com pedra. Alternativa C.', 'facil'),
('portugues', 'Figuras de linguagem', 'Na frase "Esperei uma eternidade na fila do banco", a figura de linguagem é:', 'Metáfora', 'Eufemismo', 'Hipérbole', 'Litotes', 'c', 'A hipérbole é um exagero intencional usado para dar ênfase. "Uma eternidade" exagera o tempo de espera para reforçar o incômodo. Alternativa C.', 'facil'),
('portugues', 'Figuras de linguagem', 'Em "As pedras choravam de dor com o abandono do lugar", a figura de linguagem é:', 'Metáfora', 'Personificação (ou prosopopeia)', 'Metonímia', 'Ironia', 'b', 'A personificação (prosopopeia) atribui características humanas a seres inanimados. "Pedras choravam" humaniza as pedras. Alternativa B.', 'facil'),
('portugues', 'Figuras de linguagem', 'Na frase "Ele passou desta para melhor", o termo "esta" refere-se à vida, e "melhor" à morte. Essa figura chama-se:', 'Hipérbole', 'Antítese', 'Eufemismo', 'Ironia', 'c', 'O eufemismo substitui uma expressão desagradável ou direta por outra mais suave. "Passou desta para melhor" suaviza o sentido de "morreu". Alternativa C.', 'medio');

-- 14. Funções da linguagem
INSERT INTO questions (disciplina, topico, enunciado, opcao_a, opcao_b, opcao_c, opcao_d, gabarito, explicacao, nivel_dificuldade) VALUES
('portugues', 'Funções da linguagem', 'Um texto de lei ou decreto municipal, por prezar pela clareza e objetividade das normas, tem predominância da função:', 'Emotiva', 'Poética', 'Referencial', 'Fática', 'c', 'A função referencial (ou denotativa) predomina em textos que transmitem informações objetivas sobre a realidade, como leis, notícias e documentos oficiais. Alternativa C.', 'facil'),
('portugues', 'Funções da linguagem', 'Em "Oi! Tudo bem? Como vai você?", a função da linguagem predominante é:', 'Referencial', 'Fática', 'Emotiva', 'Poética', 'b', 'A função fática visa estabelecer, manter ou encerrar o contato entre os interlocutores. Expressões de cumprimento e saudação são exemplos típicos. Alternativa B.', 'facil'),
('portugues', 'Funções da linguagem', 'Um poema que explora a sonoridade, os jogos de palavras e a forma estética da língua apresenta predominância da função:', 'Referencial', 'Apelativa', 'Poética', 'Metalinguística', 'c', 'A função poética volta a atenção para a forma da mensagem em si, explorando recursos estéticos, sonoros e visuais da linguagem. Alternativa C.', 'facil'),
('portugues', 'Funções da linguagem', 'Em um anúncio publicitário que tenta convencer o leitor a comprar um produto, predomina a função:', 'Fática', 'Emotiva', 'Referencial', 'Apelativa (ou conativa)', 'd', 'A função apelativa (conativa) centra-se no receptor, buscando influenciar seu comportamento ou convencê-lo de algo. É típica de propagandas e discursos persuasivos. Alternativa D.', 'medio'),
('portugues', 'Funções da linguagem', 'Quando um gramático explica o que é um advérbio usando a própria linguagem, está exercendo a função:', 'Emotiva', 'Referencial', 'Metalinguística', 'Fática', 'c', 'A função metalinguística ocorre quando a linguagem é usada para falar sobre ela mesma, como em gramáticas, dicionários e comentários sobre o uso da língua. Alternativa C.', 'medio');

-- 15. Variações linguísticas
INSERT INTO questions (disciplina, topico, enunciado, opcao_a, opcao_b, opcao_c, opcao_d, gabarito, explicacao, nivel_dificuldade) VALUES
('portugues', 'Variações linguísticas', 'As diferenças na fala de pessoas de diferentes regiões do país, como o sotaque nordestino e o gaúcho, são exemplos de variação:', 'Diastrática', 'Diafásica', 'Diatópica (ou dialetal)', 'Diamésica', 'c', 'A variação diatópica (geográfica ou dialetal) refere-se às diferenças linguísticas de uma região para outra dentro de um mesmo idioma. Alternativa C.', 'medio'),
('portugues', 'Variações linguísticas', 'A diferença entre a linguagem usada em uma redação formal e em uma conversa informal com amigos é exemplo de variação:', 'Diatópica', 'Diastrática', 'Diafásica', 'Histórica', 'c', 'A variação diafásica (ou de registro) ocorre de acordo com a situação comunicativa: formal ou informal, dependendo do contexto e do interlocutor. Alternativa C.', 'medio'),
('portugues', 'Variações linguísticas', 'Palavras como "vossa mercê" (que originou "você") mostram que a língua muda ao longo do tempo. Esse tipo de variação é chamado de:', 'Variação regional', 'Variação social', 'Variação histórica (ou diacrônica)', 'Variação de registro', 'c', 'A variação histórica (diacrônica) refere-se às mudanças que a língua sofre ao longo do tempo. "Vossa mercê" → "vosmecê" → "você" é um exemplo clássico. Alternativa C.', 'facil'),
('portugues', 'Variações linguísticas', 'Gírias e expressões específicas usadas por grupos profissionais (como médicos, advogados ou programadores) são exemplos de:', 'Dialeto regional', 'Norma culta', 'Variação diastrática ou jargão profissional', 'Língua escrita padrão', 'c', 'A variação diastrática relaciona-se com os grupos sociais. Jargões profissionais são variedades usadas por grupos específicos dentro de uma mesma comunidade. Alternativa C.', 'medio'),
('portugues', 'Variações linguísticas', 'Sobre as variações linguísticas, é CORRETO afirmar:', 'A norma culta é a única forma correta de se falar e escrever em português.', 'As variações linguísticas representam erros que devem ser corrigidos pela escola.', 'Todas as variedades linguísticas têm sua lógica e valor dentro de seus contextos de uso.', 'A linguagem informal é sempre inferior à linguagem formal.', 'c', 'Todas as variedades da língua são sistemas organizados e válidos dentro de seus contextos. A norma culta é exigida em contextos formais, mas não é "superior" às demais variedades. Alternativa C.', 'facil');

-- ============================================================
-- MATEMÁTICA
-- ============================================================

-- 1. Sistemas de numeração e divisibilidade
INSERT INTO questions (disciplina, topico, enunciado, opcao_a, opcao_b, opcao_c, opcao_d, gabarito, explicacao, nivel_dificuldade) VALUES
('matematica', 'Sistemas de numeração e divisibilidade', 'Qual é o menor número de 3 algarismos divisível por 2, 3 e 5 simultaneamente?', '100', '120', '150', '180', 'b', 'O MMC(2,3,5) = 30. O menor múltiplo de 30 com 3 algarismos é 30 × 4 = 120. Verificando: 120 ÷ 2 = 60, 120 ÷ 3 = 40, 120 ÷ 5 = 24. Alternativa B.', 'medio'),
('matematica', 'Sistemas de numeração e divisibilidade', 'Um número é divisível por 9 se:', 'O último algarismo for 9.', 'A soma dos seus algarismos for divisível por 9.', 'Ele for divisível por 3 e por 6.', 'O penúltimo algarismo for par.', 'b', 'O critério de divisibilidade por 9: a soma dos algarismos deve ser divisível por 9. Ex: 729 → 7+2+9 = 18, divisível por 9. Alternativa B.', 'facil'),
('matematica', 'Sistemas de numeração e divisibilidade', 'O MDC de 48 e 36 é:', '6', '12', '18', '24', 'b', 'Fatorando: 48 = 2⁴ × 3 e 36 = 2² × 3². O MDC pega os fatores comuns com menor expoente: 2² × 3 = 4 × 3 = 12. Alternativa B.', 'medio'),
('matematica', 'Sistemas de numeração e divisibilidade', 'O número 2.856 é divisível por 4 porque:', 'A soma dos algarismos é divisível por 4.', 'Os dois últimos algarismos formam um número divisível por 4.', 'Ele é par.', 'O algarismo das unidades é 6.', 'b', 'O critério de divisibilidade por 4: os dois últimos algarismos formam um número divisível por 4. Em 2.856, os dois últimos são 56, e 56 ÷ 4 = 14. Alternativa B.', 'facil'),
('matematica', 'Sistemas de numeração e divisibilidade', 'Quantos divisores tem o número 36?', '6', '7', '8', '9', 'd', '36 = 2² × 3². Número de divisores = (2+1)(2+1) = 9. Os divisores são: 1, 2, 3, 4, 6, 9, 12, 18, 36. Alternativa D.', 'medio');

-- 2. Conjuntos numéricos e operações
INSERT INTO questions (disciplina, topico, enunciado, opcao_a, opcao_b, opcao_c, opcao_d, gabarito, explicacao, nivel_dificuldade) VALUES
('matematica', 'Conjuntos numéricos e operações', 'O resultado de |–8| + |–3| – |5| é:', '0', '6', '10', '16', 'b', '|–8| = 8, |–3| = 3, |5| = 5. Então: 8 + 3 – 5 = 6. Alternativa B.', 'facil'),
('matematica', 'Conjuntos numéricos e operações', 'Qual dos seguintes números é IRRACIONAL?', '√4', '√9', '√2', '0,333...', 'c', '√4 = 2 e √9 = 3 são racionais. 0,333... = 1/3 é racional. √2 não pode ser expresso como fração, sendo irracional. Alternativa C.', 'facil'),
('matematica', 'Conjuntos numéricos e operações', 'O resultado de (–3)³ é:', '9', '–9', '27', '–27', 'd', '(–3)³ = (–3) × (–3) × (–3) = 9 × (–3) = –27. Alternativa D.', 'facil'),
('matematica', 'Conjuntos numéricos e operações', 'Se A = {1, 2, 3, 4} e B = {3, 4, 5, 6}, então A ∩ B é:', '{1, 2, 3, 4, 5, 6}', '{3, 4}', '{1, 2}', '{5, 6}', 'b', 'A interseção A ∩ B contém os elementos que pertencem a ambos os conjuntos simultaneamente: {3, 4}. Alternativa B.', 'facil'),
('matematica', 'Conjuntos numéricos e operações', 'O valor de 2⁻³ é:', '–8', '–6', '1/8', '1/6', 'c', 'Por definição, a⁻ⁿ = 1/aⁿ. Portanto, 2⁻³ = 1/2³ = 1/8. Alternativa C.', 'medio');

-- 3. Proporcionalidade e porcentagem
INSERT INTO questions (disciplina, topico, enunciado, opcao_a, opcao_b, opcao_c, opcao_d, gabarito, explicacao, nivel_dificuldade) VALUES
('matematica', 'Proporcionalidade e porcentagem', 'Um produto custava R$ 80,00 e sofreu um aumento de 15%. Qual é o novo preço?', 'R$ 88,00', 'R$ 90,00', 'R$ 92,00', 'R$ 95,00', 'c', 'Aumento = 15% de 80 = 0,15 × 80 = R$ 12,00. Novo preço = 80 + 12 = R$ 92,00. Alternativa C.', 'facil'),
('matematica', 'Proporcionalidade e porcentagem', 'Uma prefeitura tem 240 servidores, dos quais 30% são do sexo feminino. Quantas servidoras há?', '60', '72', '80', '96', 'b', '30% de 240 = 0,30 × 240 = 72. Alternativa B.', 'facil'),
('matematica', 'Proporcionalidade e porcentagem', 'Se 4 máquinas produzem 200 peças em 5 horas, quantas peças 6 máquinas produzem em 8 horas?', '380', '420', '480', '540', 'c', 'Produção por máquina por hora = 200 ÷ (4 × 5) = 10 peças. 6 máquinas em 8 horas: 6 × 8 × 10 = 480 peças. Alternativa C.', 'medio'),
('matematica', 'Proporcionalidade e porcentagem', 'Um salário de R$ 2.000,00 teve redução de 10% e depois aumento de 10%. O salário final é:', 'R$ 2.000,00', 'R$ 1.980,00', 'R$ 2.020,00', 'R$ 1.960,00', 'b', 'Após redução de 10%: 2000 × 0,9 = 1800. Após aumento de 10%: 1800 × 1,1 = 1980. O salário final é R$ 1.980,00. Alternativa B.', 'medio'),
('matematica', 'Proporcionalidade e porcentagem', 'Duas grandezas A e B são inversamente proporcionais. Se A = 6 e B = 4, qual é o valor de B quando A = 8?', '2', '3', '4', '5', 'b', 'Grandezas inversamente proporcionais: A × B = constante. 6 × 4 = 24. Se A = 8: 8 × B = 24, logo B = 3. Alternativa B.', 'medio');

-- 4. Funções e equações
INSERT INTO questions (disciplina, topico, enunciado, opcao_a, opcao_b, opcao_c, opcao_d, gabarito, explicacao, nivel_dificuldade) VALUES
('matematica', 'Funções e equações', 'A solução da equação 3x – 7 = 2x + 5 é:', 'x = 2', 'x = 10', 'x = 12', 'x = –12', 'c', '3x – 7 = 2x + 5 → 3x – 2x = 5 + 7 → x = 12. Alternativa C.', 'facil'),
('matematica', 'Funções e equações', 'As raízes da equação x² – 5x + 6 = 0 são:', 'x = 1 e x = 6', 'x = 2 e x = 3', 'x = –2 e x = –3', 'x = –1 e x = 6', 'b', 'Usando Bhaskara ou fatoração: x² – 5x + 6 = (x – 2)(x – 3) = 0. Portanto x = 2 ou x = 3. Alternativa B.', 'medio'),
('matematica', 'Funções e equações', 'Se f(x) = 2x + 3, o valor de f(4) é:', '8', '10', '11', '14', 'c', 'f(4) = 2(4) + 3 = 8 + 3 = 11. Alternativa C.', 'facil'),
('matematica', 'Funções e equações', 'O discriminante (Δ) de uma equação do 2º grau é negativo. Isso indica que a equação:', 'Possui duas raízes reais iguais.', 'Possui duas raízes reais distintas.', 'Não possui raízes reais.', 'Possui infinitas soluções.', 'c', 'Quando Δ < 0, a equação do 2º grau não possui raízes reais (as raízes são complexas). Alternativa C.', 'medio'),
('matematica', 'Funções e equações', 'Uma função do 1º grau f(x) = ax + b é crescente quando:', 'a < 0', 'a = 0', 'a > 0', 'b > 0', 'c', 'A função linear f(x) = ax + b é crescente quando o coeficiente angular a > 0 e decrescente quando a < 0. Alternativa C.', 'facil');

-- 5. Trigonometria
INSERT INTO questions (disciplina, topico, enunciado, opcao_a, opcao_b, opcao_c, opcao_d, gabarito, explicacao, nivel_dificuldade) VALUES
('matematica', 'Trigonometria', 'Em um triângulo retângulo, o seno de um ângulo agudo é definido como:', 'cateto adjacente / hipotenusa', 'cateto oposto / cateto adjacente', 'cateto oposto / hipotenusa', 'hipotenusa / cateto oposto', 'c', 'O seno de um ângulo em um triângulo retângulo é a razão entre o cateto oposto ao ângulo e a hipotenusa: sen = cateto oposto / hipotenusa. Alternativa C.', 'facil'),
('matematica', 'Trigonometria', 'O valor de sen 30° é:', '√3/2', '1/2', '√2/2', '1', 'b', 'Os valores trigonométricos notáveis: sen 30° = 1/2, sen 45° = √2/2, sen 60° = √3/2. Alternativa B.', 'facil'),
('matematica', 'Trigonometria', 'Um poste vertical de 10 m de altura projeta uma sombra de 10√3 m no chão. Qual é o ângulo de elevação do sol?', '30°', '45°', '60°', '90°', 'a', 'tan θ = altura / sombra = 10 / (10√3) = 1/√3. Como tan 30° = 1/√3, o ângulo é 30°. Alternativa A.', 'medio'),
('matematica', 'Trigonometria', 'A identidade trigonométrica fundamental é:', 'sen²x + cos²x = 0', 'sen²x – cos²x = 1', 'sen²x + cos²x = 1', 'senx × cosx = 1', 'c', 'A identidade trigonométrica fundamental é sen²x + cos²x = 1, válida para qualquer ângulo x. Alternativa C.', 'facil'),
('matematica', 'Trigonometria', 'Em um triângulo retângulo com catetos de 3 e 4, a hipotenusa mede:', '5', '6', '7', '√7', 'a', 'Pelo Teorema de Pitágoras: h² = 3² + 4² = 9 + 16 = 25. h = √25 = 5. Alternativa A.', 'facil');

-- 6. Progressões
INSERT INTO questions (disciplina, topico, enunciado, opcao_a, opcao_b, opcao_c, opcao_d, gabarito, explicacao, nivel_dificuldade) VALUES
('matematica', 'Progressões', 'Em uma PA com primeiro termo a₁ = 3 e razão r = 4, qual é o 6º termo?', '19', '23', '27', '31', 'b', 'Fórmula do termo geral: aₙ = a₁ + (n–1)r. a₆ = 3 + 5 × 4 = 3 + 20 = 23. Alternativa B.', 'facil'),
('matematica', 'Progressões', 'A soma dos 10 primeiros termos de uma PA com a₁ = 2 e r = 3 é:', '145', '155', '165', '175', 'b', 'Sₙ = n/2 × (2a₁ + (n–1)r). S₁₀ = 10/2 × (4 + 27) = 5 × 31 = 155. Alternativa B.', 'medio'),
('matematica', 'Progressões', 'Em uma PG com a₁ = 2 e razão q = 3, o 4º termo é:', '18', '54', '162', '27', 'b', 'Fórmula do termo geral: aₙ = a₁ × q^(n–1). a₄ = 2 × 3³ = 2 × 27 = 54. Alternativa B.', 'medio'),
('matematica', 'Progressões', 'A sequência 2, 6, 18, 54, ... é uma:', 'PA com razão 4', 'PG com razão 3', 'PA com razão 3', 'PG com razão 4', 'b', 'Cada termo é obtido multiplicando o anterior por 3: 2×3=6, 6×3=18, 18×3=54. É uma PG com razão q = 3. Alternativa B.', 'facil'),
('matematica', 'Progressões', 'A soma de uma PG infinita com a₁ = 4 e razão q = 1/2 é:', '6', '8', '10', '12', 'b', 'Soma da PG infinita (|q| < 1): S = a₁ / (1 – q) = 4 / (1 – 1/2) = 4 / (1/2) = 8. Alternativa B.', 'medio');

-- 7. Análise combinatória
INSERT INTO questions (disciplina, topico, enunciado, opcao_a, opcao_b, opcao_c, opcao_d, gabarito, explicacao, nivel_dificuldade) VALUES
('matematica', 'Análise combinatória', 'De quantas formas 5 pessoas podem se sentar em uma fila de 5 cadeiras?', '25', '60', '100', '120', 'd', 'Permutação de 5 elementos: P₅ = 5! = 5 × 4 × 3 × 2 × 1 = 120. Alternativa D.', 'facil'),
('matematica', 'Análise combinatória', 'Quantos subconjuntos com 2 elementos podem ser formados com um conjunto de 5 elementos?', '8', '10', '12', '20', 'b', 'Combinação C(5,2) = 5!/(2!×3!) = (5×4)/(2×1) = 10. Alternativa B.', 'facil'),
('matematica', 'Análise combinatória', 'Uma senha de 4 dígitos distintos é formada usando os algarismos de 1 a 6. Quantas senhas são possíveis?', '180', '240', '320', '360', 'd', 'Arranjo A(6,4) = 6!/(6–4)! = 6!/2! = 720/2 = 360. Alternativa D.', 'medio'),
('matematica', 'Análise combinatória', 'O valor de 6! / 4! é:', '12', '24', '30', '42', 'c', '6!/4! = (6 × 5 × 4!)/ 4! = 6 × 5 = 30. Alternativa C.', 'facil'),
('matematica', 'Análise combinatória', 'Em um grupo de 4 homens e 3 mulheres, de quantas formas pode-se formar uma comissão com 2 homens e 2 mulheres?', '12', '18', '24', '36', 'b', 'C(4,2) × C(3,2) = 6 × 3 = 18. Alternativa B.', 'medio');

-- 8. Matrizes e sistemas lineares
INSERT INTO questions (disciplina, topico, enunciado, opcao_a, opcao_b, opcao_c, opcao_d, gabarito, explicacao, nivel_dificuldade) VALUES
('matematica', 'Matrizes e sistemas lineares', 'O determinante da matriz [[2, 3], [1, 4]] é:', '5', '8', '11', '6', 'a', 'det = (2×4) – (3×1) = 8 – 3 = 5. Alternativa A.', 'facil'),
('matematica', 'Matrizes e sistemas lineares', 'Uma matriz de ordem 2×3 possui:', '5 elementos', '6 elementos', '9 elementos', '12 elementos', 'b', 'Uma matriz de ordem m×n possui m×n elementos. 2×3 = 6 elementos. Alternativa B.', 'facil'),
('matematica', 'Matrizes e sistemas lineares', 'O sistema linear {x + y = 5 e x – y = 1} tem como solução:', 'x = 2, y = 3', 'x = 3, y = 2', 'x = 4, y = 1', 'x = 1, y = 4', 'b', 'Somando as equações: 2x = 6 → x = 3. Substituindo: 3 + y = 5 → y = 2. Alternativa B.', 'facil'),
('matematica', 'Matrizes e sistemas lineares', 'Um sistema linear é classificado como IMPOSSÍVEL quando:', 'Possui exatamente uma solução.', 'Possui infinitas soluções.', 'Não possui solução.', 'O determinante é diferente de zero.', 'c', 'Um sistema impossível é aquele que não admite nenhuma solução (as equações são inconsistentes entre si). Alternativa C.', 'facil'),
('matematica', 'Matrizes e sistemas lineares', 'A matriz transposta de [[1, 2], [3, 4]] é:', '[[1, 3], [2, 4]]', '[[4, 3], [2, 1]]', '[[2, 1], [4, 3]]', '[[1, 2], [3, 4]]', 'a', 'A transposta troca linhas por colunas: a linha 1 [1,2] torna-se coluna 1, e a linha 2 [3,4] torna-se coluna 2: [[1,3],[2,4]]. Alternativa A.', 'medio');

-- 9. Geometria plana
INSERT INTO questions (disciplina, topico, enunciado, opcao_a, opcao_b, opcao_c, opcao_d, gabarito, explicacao, nivel_dificuldade) VALUES
('matematica', 'Geometria plana', 'A área de um retângulo com base 8 m e altura 5 m é:', '26 m²', '40 m²', '13 m²', '80 m²', 'b', 'Área do retângulo = base × altura = 8 × 5 = 40 m². Alternativa B.', 'facil'),
('matematica', 'Geometria plana', 'A área de um círculo com raio 7 cm é (π ≈ 3,14):', '43,96 cm²', '153,86 cm²', '21,98 cm²', '44 cm²', 'b', 'A = π × r² = 3,14 × 7² = 3,14 × 49 = 153,86 cm². Alternativa B.', 'facil'),
('matematica', 'Geometria plana', 'Um triângulo tem base 10 cm e altura 6 cm. Sua área é:', '30 cm²', '60 cm²', '15 cm²', '50 cm²', 'a', 'Área do triângulo = (base × altura) / 2 = (10 × 6) / 2 = 30 cm². Alternativa A.', 'facil'),
('matematica', 'Geometria plana', 'A soma dos ângulos internos de um polígono de 6 lados (hexágono) é:', '540°', '720°', '900°', '1080°', 'b', 'Soma dos ângulos internos = (n – 2) × 180°. Para n = 6: (6–2) × 180 = 4 × 180 = 720°. Alternativa B.', 'medio'),
('matematica', 'Geometria plana', 'O perímetro de um quadrado com lado de 9 cm é:', '18 cm', '27 cm', '36 cm', '81 cm', 'c', 'Perímetro do quadrado = 4 × lado = 4 × 9 = 36 cm. Alternativa C.', 'facil');

-- 10. Geometria espacial
INSERT INTO questions (disciplina, topico, enunciado, opcao_a, opcao_b, opcao_c, opcao_d, gabarito, explicacao, nivel_dificuldade) VALUES
('matematica', 'Geometria espacial', 'O volume de um cubo com aresta de 4 cm é:', '16 cm³', '48 cm³', '64 cm³', '96 cm³', 'c', 'Volume do cubo = a³ = 4³ = 64 cm³. Alternativa C.', 'facil'),
('matematica', 'Geometria espacial', 'O volume de um cilindro com raio 3 cm e altura 10 cm é (π ≈ 3,14):', '94,2 cm³', '188,4 cm³', '282,6 cm³', '314 cm³', 'c', 'V = π × r² × h = 3,14 × 9 × 10 = 282,6 cm³. Alternativa C.', 'medio'),
('matematica', 'Geometria espacial', 'A área total de um cubo com aresta de 5 cm é:', '100 cm²', '125 cm²', '150 cm²', '175 cm²', 'c', 'Área total do cubo = 6 × a² = 6 × 25 = 150 cm². Alternativa C.', 'facil'),
('matematica', 'Geometria espacial', 'Um cone tem raio da base igual a 3 cm e altura igual a 4 cm. O volume desse cone é (π ≈ 3,14):', '37,68 cm³', '50,24 cm³', '62,80 cm³', '75,36 cm³', 'a', 'V = (1/3) × π × r² × h = (1/3) × 3,14 × 9 × 4 = (1/3) × 113,04 = 37,68 cm³. Alternativa A.', 'medio'),
('matematica', 'Geometria espacial', 'O volume de uma esfera com raio 6 cm é (π ≈ 3,14):', '452,16 cm³', '678,24 cm³', '904,32 cm³', '1.130,4 cm³', 'c', 'V = (4/3) × π × r³ = (4/3) × 3,14 × 216 = (4/3) × 678,24 = 904,32 cm³. Alternativa C.', 'medio');

-- 11. Geometria analítica
INSERT INTO questions (disciplina, topico, enunciado, opcao_a, opcao_b, opcao_c, opcao_d, gabarito, explicacao, nivel_dificuldade) VALUES
('matematica', 'Geometria analítica', 'A distância entre os pontos A(1, 2) e B(4, 6) é:', '4', '5', '6', '7', 'b', 'd = √((4–1)² + (6–2)²) = √(9 + 16) = √25 = 5. Alternativa B.', 'medio'),
('matematica', 'Geometria analítica', 'O ponto médio entre A(2, 4) e B(6, 8) é:', '(3, 5)', '(4, 6)', '(5, 7)', '(8, 12)', 'b', 'Ponto médio = ((x₁+x₂)/2, (y₁+y₂)/2) = ((2+6)/2, (4+8)/2) = (4, 6). Alternativa B.', 'facil'),
('matematica', 'Geometria analítica', 'A equação da reta que passa pela origem com coeficiente angular 3 é:', 'y = 3', 'y = 3x', 'y = x + 3', 'x = 3y', 'b', 'A equação da reta com coeficiente angular m e passando pela origem é y = mx. Com m = 3: y = 3x. Alternativa B.', 'facil'),
('matematica', 'Geometria analítica', 'O coeficiente angular de uma reta que passa pelos pontos A(1, 2) e B(3, 8) é:', '2', '3', '4', '5', 'b', 'm = (y₂ – y₁)/(x₂ – x₁) = (8–2)/(3–1) = 6/2 = 3. Alternativa B.', 'medio'),
('matematica', 'Geometria analítica', 'Duas retas são PERPENDICULARES quando o produto de seus coeficientes angulares é:', '0', '1', '–1', '2', 'c', 'Duas retas são perpendiculares quando m₁ × m₂ = –1, ou seja, os coeficientes angulares são inversos e opostos. Alternativa C.', 'medio');

-- 12. Estatística básica
INSERT INTO questions (disciplina, topico, enunciado, opcao_a, opcao_b, opcao_c, opcao_d, gabarito, explicacao, nivel_dificuldade) VALUES
('matematica', 'Estatística básica', 'A média aritmética das notas 7, 8, 6, 9 e 10 é:', '7,5', '8,0', '8,5', '9,0', 'b', 'Média = (7+8+6+9+10)/5 = 40/5 = 8,0. Alternativa B.', 'facil'),
('matematica', 'Estatística básica', 'A mediana do conjunto {3, 5, 7, 9, 11} é:', '5', '7', '8', '9', 'b', 'Com 5 elementos em ordem crescente, a mediana é o elemento central, o 3º elemento: 7. Alternativa B.', 'facil'),
('matematica', 'Estatística básica', 'A moda do conjunto {2, 3, 3, 4, 5, 5, 5, 6} é:', '3', '4', '5', '6', 'c', 'A moda é o valor que aparece com maior frequência. O número 5 aparece 3 vezes, sendo a moda. Alternativa C.', 'facil'),
('matematica', 'Estatística básica', 'O desvio padrão é uma medida de:', 'Tendência central dos dados.', 'Dispersão ou variabilidade dos dados em relação à média.', 'Frequência dos dados.', 'Posição relativa de um valor no conjunto.', 'b', 'O desvio padrão mede o quanto os dados se afastam da média, sendo uma medida de dispersão ou variabilidade. Alternativa B.', 'medio'),
('matematica', 'Estatística básica', 'Em uma pesquisa com 100 pessoas, 35 preferem a opção A e 65 preferem a opção B. A frequência relativa da opção A é:', '35', '0,35', '65%', '0,65', 'b', 'Frequência relativa = frequência absoluta / total = 35/100 = 0,35 (ou 35%). Alternativa B.', 'facil');

-- 13. Probabilidades
INSERT INTO questions (disciplina, topico, enunciado, opcao_a, opcao_b, opcao_c, opcao_d, gabarito, explicacao, nivel_dificuldade) VALUES
('matematica', 'Probabilidades', 'Ao lançar um dado honesto de 6 faces, a probabilidade de obter um número par é:', '1/6', '1/3', '1/2', '2/3', 'c', 'Números pares no dado: {2, 4, 6} = 3 resultados favoráveis. P = 3/6 = 1/2. Alternativa C.', 'facil'),
('matematica', 'Probabilidades', 'Uma urna contém 4 bolas vermelhas e 6 bolas azuis. A probabilidade de retirar uma bola azul ao acaso é:', '2/5', '3/5', '4/10', '1/3', 'b', 'Total de bolas = 10. Bolas azuis = 6. P = 6/10 = 3/5. Alternativa B.', 'facil'),
('matematica', 'Probabilidades', 'Se a probabilidade de um evento ocorrer é 0,3, a probabilidade de ele NÃO ocorrer é:', '0,3', '0,6', '0,7', '1,3', 'c', 'P(evento não ocorrer) = 1 – P(evento) = 1 – 0,3 = 0,7. Alternativa C.', 'facil'),
('matematica', 'Probabilidades', 'Dois dados são lançados simultaneamente. A probabilidade de a soma ser igual a 7 é:', '1/6', '5/36', '6/36', '7/36', 'a', 'Pares que somam 7: (1,6),(2,5),(3,4),(4,3),(5,2),(6,1) = 6 casos. Total = 36. P = 6/36 = 1/6. Alternativa A.', 'medio'),
('matematica', 'Probabilidades', 'A probabilidade de dois eventos independentes A e B ocorrerem simultaneamente é:', 'P(A) + P(B)', 'P(A) – P(B)', 'P(A) × P(B)', 'P(A) / P(B)', 'c', 'Para eventos independentes, a probabilidade da interseção é o produto das probabilidades: P(A ∩ B) = P(A) × P(B). Alternativa C.', 'medio');

-- ============================================================
-- NOÇÕES DE INFORMÁTICA
-- ============================================================

-- 1. Sistemas operacionais
INSERT INTO questions (disciplina, topico, enunciado, opcao_a, opcao_b, opcao_c, opcao_d, gabarito, explicacao, nivel_dificuldade) VALUES
('informatica', 'Sistemas operacionais', 'Qual é a principal função de um sistema operacional?', 'Criar documentos de texto e planilhas.', 'Gerenciar os recursos do hardware e fornecer serviços para os programas.', 'Conectar o computador à internet.', 'Armazenar arquivos permanentemente no disco.', 'b', 'O sistema operacional é o software responsável por gerenciar os recursos de hardware (processador, memória, disco) e fornecer uma interface entre o hardware e os demais programas. Alternativa B.', 'facil'),
('informatica', 'Sistemas operacionais', 'No Windows, o atalho de teclado utilizado para copiar um arquivo ou texto selecionado é:', 'Ctrl + X', 'Ctrl + V', 'Ctrl + C', 'Ctrl + Z', 'c', 'Ctrl + C é o atalho para copiar. Ctrl + X recorta, Ctrl + V cola e Ctrl + Z desfaz a última ação. Alternativa C.', 'facil'),
('informatica', 'Sistemas operacionais', 'A "Lixeira" do Windows tem como função:', 'Apagar definitivamente os arquivos do computador.', 'Armazenar temporariamente os arquivos excluídos, permitindo sua recuperação.', 'Compactar arquivos para liberar espaço em disco.', 'Fazer backup automático dos arquivos importantes.', 'b', 'A Lixeira é um local temporário onde os arquivos excluídos são armazenados antes da exclusão definitiva, permitindo que sejam restaurados se necessário. Alternativa B.', 'facil'),
('informatica', 'Sistemas operacionais', 'No Windows Explorer (Explorador de Arquivos), para selecionar múltiplos arquivos não consecutivos, deve-se manter pressionada a tecla:', 'Shift', 'Alt', 'Ctrl', 'Tab', 'c', 'Para selecionar múltiplos arquivos não consecutivos no Windows, mantém-se a tecla Ctrl pressionada enquanto se clica em cada arquivo. O Shift seleciona um intervalo contínuo. Alternativa C.', 'facil'),
('informatica', 'Sistemas operacionais', 'Qual dos sistemas operacionais a seguir é de código aberto (open source)?', 'Windows 10', 'macOS', 'Linux', 'iOS', 'c', 'Linux é um sistema operacional de código aberto (open source), o que significa que seu código-fonte é disponibilizado publicamente e pode ser modificado livremente. Alternativa C.', 'facil');

-- 2. Aplicativos de escritório
INSERT INTO questions (disciplina, topico, enunciado, opcao_a, opcao_b, opcao_c, opcao_d, gabarito, explicacao, nivel_dificuldade) VALUES
('informatica', 'Aplicativos de escritório', 'No Microsoft Word, qual atalho de teclado é usado para salvar um documento?', 'Ctrl + P', 'Ctrl + S', 'Ctrl + N', 'Ctrl + O', 'b', 'Ctrl + S (de "Save") é o atalho para salvar o documento no Word e na maioria dos aplicativos Windows. Alternativa B.', 'facil'),
('informatica', 'Aplicativos de escritório', 'No Microsoft Excel, a fórmula para somar um intervalo de células de A1 até A10 é:', '=SOMA(A1,A10)', '=SOMA(A1:A10)', '=TOTAL(A1-A10)', '=SOMAR(A1 A10)', 'b', 'A função SOMA no Excel usa o símbolo ":" para indicar um intervalo de células: =SOMA(A1:A10). A vírgula separaria células específicas não consecutivas. Alternativa B.', 'facil'),
('informatica', 'Aplicativos de escritório', 'No Microsoft PowerPoint, cada tela de apresentação é chamada de:', 'Página', 'Quadro', 'Slide', 'Frame', 'c', 'No PowerPoint, cada unidade da apresentação é chamada de "slide". O conjunto de slides forma a apresentação. Alternativa C.', 'facil'),
('informatica', 'Aplicativos de escritório', 'No Excel, se a célula A1 contém o valor 10 e A2 contém 5, a fórmula =A1/A2 retornará:', '2', '5', '15', '50', 'a', '=A1/A2 = 10/5 = 2. A barra "/" representa divisão nas fórmulas do Excel. Alternativa A.', 'facil'),
('informatica', 'Aplicativos de escritório', 'O formato de arquivo padrão do Microsoft Word 2016 em diante é:', '.doc', '.docx', '.txt', '.pdf', 'b', 'A partir do Office 2007, o formato padrão do Word passou a ser .docx (baseado em XML), enquanto .doc era o formato das versões anteriores. Alternativa B.', 'facil');

-- 3. Internet e computação em nuvem
INSERT INTO questions (disciplina, topico, enunciado, opcao_a, opcao_b, opcao_c, opcao_d, gabarito, explicacao, nivel_dificuldade) VALUES
('informatica', 'Internet e computação em nuvem', 'O protocolo HTTPS, em relação ao HTTP, oferece:', 'Navegação mais rápida.', 'Comunicação criptografada e mais segura entre o navegador e o servidor.', 'Acesso a conteúdo exclusivo da deep web.', 'Melhor qualidade de imagens nas páginas.', 'b', 'O HTTPS (HTTP Secure) utiliza criptografia SSL/TLS para proteger os dados transmitidos entre o navegador e o servidor web, garantindo segurança e privacidade. Alternativa B.', 'medio'),
('informatica', 'Internet e computação em nuvem', 'Computação em nuvem (cloud computing) refere-se a:', 'Um tipo especial de hardware para processamento gráfico.', 'O armazenamento e processamento de dados em servidores remotos acessados pela internet.', 'Um sistema de backup exclusivo para empresas de grande porte.', 'Uma tecnologia de redes sem fio de alta velocidade.', 'b', 'Computação em nuvem consiste em usar servidores remotos pela internet para armazenar, gerenciar e processar dados, em vez de usar um servidor local ou computador pessoal. Alternativa B.', 'facil'),
('informatica', 'Internet e computação em nuvem', 'Qual dos serviços abaixo é um exemplo de computação em nuvem?', 'Processador Intel Core i7', 'Google Drive', 'Monitor LED Full HD', 'Teclado USB', 'b', 'Google Drive é um serviço de armazenamento em nuvem que permite guardar e acessar arquivos remotamente pela internet. Alternativa B.', 'facil'),
('informatica', 'Internet e computação em nuvem', 'Um navegador de internet (browser) tem como função:', 'Criar e editar documentos de texto.', 'Gerenciar arquivos no disco rígido.', 'Acessar e exibir páginas da World Wide Web.', 'Proteger o computador contra vírus.', 'c', 'O navegador (browser) é o software que permite acessar, interpretar e exibir páginas web. Exemplos: Chrome, Firefox, Edge. Alternativa C.', 'facil'),
('informatica', 'Internet e computação em nuvem', 'O que é um endereço IP?', 'O nome de usuário usado para fazer login em um site.', 'Um identificador numérico único atribuído a cada dispositivo em uma rede.', 'O protocolo usado para enviar e-mails.', 'O endereço físico de um computador gravado no hardware.', 'b', 'O endereço IP (Internet Protocol) é um número único que identifica cada dispositivo conectado a uma rede, permitindo o roteamento correto dos dados. Alternativa B.', 'medio');

-- 4. E-mail e redes sociais
INSERT INTO questions (disciplina, topico, enunciado, opcao_a, opcao_b, opcao_c, opcao_d, gabarito, explicacao, nivel_dificuldade) VALUES
('informatica', 'E-mail e redes sociais', 'Em um e-mail, o campo "CC" significa:', 'Cópia Oculta', 'Com Criptografia', 'Com Cópia', 'Cópia Confirmada', 'c', 'CC significa "Com Cópia" (Carbon Copy). Ao inserir um endereço no campo CC, essa pessoa recebe uma cópia do e-mail e todos os destinatários conseguem ver quem está em cópia. Alternativa C.', 'facil'),
('informatica', 'E-mail e redes sociais', 'O campo "CCO" (ou "BCC" em inglês) em um e-mail serve para:', 'Enviar o e-mail com criptografia avançada.', 'Adicionar destinatários em cópia oculta, sem que os demais saibam.', 'Confirmar o recebimento do e-mail automaticamente.', 'Anexar arquivos de grande tamanho.', 'b', 'CCO significa "Cópia de Carbono Oculta" (Blind Carbon Copy). Os destinatários em CCO recebem o e-mail, mas nenhum outro destinatário sabe que eles também o receberam. Alternativa B.', 'medio'),
('informatica', 'E-mail e redes sociais', 'Uma prática de segurança recomendada ao usar redes sociais é:', 'Usar a mesma senha para todas as contas para facilitar o acesso.', 'Compartilhar sua senha com pessoas de confiança.', 'Utilizar senhas fortes e diferentes para cada conta, ativando a verificação em duas etapas.', 'Aceitar todas as solicitações de amizade para ampliar sua rede de contatos.', 'c', 'Senhas fortes e únicas para cada conta, combinadas com verificação em duas etapas (2FA), são práticas fundamentais de segurança em redes sociais. Alternativa C.', 'facil'),
('informatica', 'E-mail e redes sociais', 'O que é "phishing"?', 'Um tipo de antivírus para proteção de e-mails.', 'Uma técnica de ataque que usa mensagens falsas para enganar o usuário e roubar dados.', 'Um protocolo de envio seguro de e-mails.', 'Um filtro de spam instalado no servidor de e-mail.', 'b', 'Phishing é uma técnica de ataque cibernético em que o criminoso se passa por uma entidade confiável (banco, empresa) para induzir a vítima a fornecer dados pessoais, senhas ou informações financeiras. Alternativa B.', 'medio'),
('informatica', 'E-mail e redes sociais', 'Ao receber um e-mail de remetente desconhecido com um arquivo anexo, a atitude mais segura é:', 'Abrir o anexo rapidamente para verificar seu conteúdo.', 'Encaminhar o e-mail para todos os contatos avisando sobre o arquivo.', 'Não abrir o anexo e deletar o e-mail, pois pode conter malware.', 'Responder ao remetente pedindo mais informações.', 'c', 'Arquivos anexos em e-mails de remetentes desconhecidos são um vetor comum de distribuição de malware (vírus, ransomware). A atitude segura é não abrir e excluir o e-mail. Alternativa C.', 'facil');

-- 5. Segurança da informação
INSERT INTO questions (disciplina, topico, enunciado, opcao_a, opcao_b, opcao_c, opcao_d, gabarito, explicacao, nivel_dificuldade) VALUES
('informatica', 'Segurança da informação', 'O princípio da CONFIDENCIALIDADE em segurança da informação significa:', 'Garantir que os dados estejam sempre disponíveis quando necessários.', 'Assegurar que os dados não sejam alterados por pessoas não autorizadas.', 'Garantir que as informações sejam acessadas apenas por pessoas autorizadas.', 'Confirmar a identidade do usuário antes do acesso.', 'c', 'Confidencialidade garante que as informações sejam acessíveis somente por pessoas autorizadas. Os três pilares da segurança da informação são: Confidencialidade, Integridade e Disponibilidade (CID). Alternativa C.', 'medio'),
('informatica', 'Segurança da informação', 'Um "vírus de computador" é:', 'Um hardware defeituoso que danifica o processador.', 'Um programa malicioso que se replica e pode causar danos ao sistema.', 'Uma falha física no disco rígido.', 'Um protocolo de internet com vulnerabilidades de segurança.', 'b', 'Um vírus de computador é um software malicioso (malware) capaz de se replicar e se espalhar para outros arquivos ou sistemas, podendo causar danos, roubar dados ou comprometer o funcionamento do computador. Alternativa B.', 'facil'),
('informatica', 'Segurança da informação', 'O que é um firewall?', 'Um programa para recuperar arquivos excluídos.', 'Um sistema de segurança que monitora e controla o tráfego de rede, bloqueando acessos não autorizados.', 'Um tipo de antivírus especializado em vírus de e-mail.', 'Um dispositivo para acelerar a conexão com a internet.', 'b', 'O firewall é uma barreira de segurança que monitora e filtra o tráfego de entrada e saída de uma rede ou computador, bloqueando conexões não autorizadas ou suspeitas. Alternativa B.', 'medio'),
('informatica', 'Segurança da informação', 'Uma senha segura deve:', 'Conter apenas letras minúsculas para ser fácil de lembrar.', 'Ser igual ao seu nome ou data de nascimento.', 'Ter no mínimo 8 caracteres, combinando letras maiúsculas, minúsculas, números e símbolos.', 'Ser compartilhada com colegas de trabalho de confiança.', 'c', 'Uma senha forte deve ter comprimento adequado (mínimo 8 caracteres) e combinar diferentes tipos de caracteres: letras maiúsculas, minúsculas, números e símbolos especiais, dificultando ataques de força bruta. Alternativa C.', 'facil'),
('informatica', 'Segurança da informação', 'O que é um "ransomware"?', 'Um tipo de antivírus que protege contra sequestros de dados.', 'Um malware que criptografa os arquivos da vítima e exige pagamento (resgate) para liberá-los.', 'Um software legítimo de backup de dados.', 'Um protocolo de comunicação segura para redes corporativas.', 'b', 'Ransomware é um tipo de malware que criptografa os arquivos do sistema infectado e exige um resgate (geralmente em criptomoeda) para fornecer a chave de descriptografia. Alternativa B.', 'medio');
